/**
 * GENERATED by scripts/reconcile_champions.ts — do not hand-edit.
 * Derived from the active reigns in src/lib/championship-history.ts
 * (+ fighter gender from the DB). To change a champion, edit
 * championship-history.ts and run `pnpm champions:reconcile`.
 * (No timestamp here on purpose: the file must be byte-identical on
 * no-change days so the cron commit gate stays quiet.)
 */

export interface ChampionEntry {
  slug: string;
  division: string;
  divisionShort: string;
  isInterim?: boolean;
}

export const CURRENT_CHAMPIONS: readonly ChampionEntry[] = [
  { slug: "tom-aspinall-399afb", division: "Heavyweight", divisionShort: "HW" }, // Tom Aspinall, since 2025-06-21
  { slug: "carlos-ulberg-9014c0", division: "Light Heavyweight", divisionShort: "LHW" }, // Carlos Ulberg, since 2026-04-11
  { slug: "sean-strickland-0d8011", division: "Middleweight", divisionShort: "MW" }, // Sean Strickland, since 2026-05-09
  { slug: "islam-makhachev-275aca", division: "Welterweight", divisionShort: "WW" }, // Islam Makhachev, since 2025-11-15
  { slug: "justin-gaethje-9e8f6c", division: "Lightweight", divisionShort: "LW" }, // Justin Gaethje, since 2026-06-14
  { slug: "alexander-volkanovski-e12489", division: "Featherweight", divisionShort: "FW" }, // Alexander Volkanovski, since 2025-04-12
  { slug: "petr-yan-d661ce", division: "Bantamweight", divisionShort: "BW" }, // Petr Yan, since 2025-12-06
  { slug: "joshua-van-17e976", division: "Flyweight", divisionShort: "FLW" }, // Joshua Van, since 2025-12-06
  { slug: "mackenzie-dern-7447e9", division: "Women's Strawweight", divisionShort: "W-SW" }, // Mackenzie Dern, since 2025-10-25
  { slug: "valentina-shevchenko-132deb", division: "Women's Flyweight", divisionShort: "W-FLW" }, // Valentina Shevchenko, since 2024-09-14
  { slug: "kayla-harrison-1af117", division: "Women's Bantamweight", divisionShort: "W-BW" }, // Kayla Harrison, since 2025-06-07
];

export const CHAMPION_SLUGS: readonly string[] = CURRENT_CHAMPIONS.map(
  (c) => c.slug,
);

/** Quick lookup by slug for the strip rendering path. */
export const CHAMPION_BY_SLUG: Map<string, ChampionEntry> = new Map(
  CURRENT_CHAMPIONS.map((c) => [c.slug, c]),
);
