/**
 * Title-fight bout IDs — GENERATED by scripts/derive_title_fights.ts.
 *
 * Do not hand-edit. To extend coverage, add reigns to
 * championship-history.ts or challenges to title-challenger-history.ts,
 * then re-run: pnpm tsx scripts/derive_title_fights.ts
 *
 * Why a curated set exists: bout.is_title_fight from the UFCStats scrape
 * is unreliable — it flags whole main-card slates on title-headlined
 * events. This list is derived instead from the two hand-verified history
 * files: every completed bout a champion had in their division during a
 * reign, plus every lost title challenge.
 *
 * 398 bouts.
 */

const CURATED_TITLE_BOUT_IDS: readonly string[] = [
  "3bc924a6-9179-40bb-8a86-f354bd527e6d", // 2026-08-15 · UFC 330: Makhachev vs. Machado Garry · Islam Makhachev vs Ian Machado Garry
  "dc68d875-c4c2-4cee-b65e-89176608ef8c", // 2026-08-15 · UFC 330: Makhachev vs. Machado Garry · Mackenzie Dern vs Gillian Robertson
  "ab113f8b-001c-4195-8cbd-f0c84bd37be3", // 2026-06-14 · UFC Freedom 250 · Justin Gaethje vs Ilia Topuria
  "e7569169-e92d-4f34-ab06-6cedb9bb4789", // 2026-05-09 · UFC 328: Chimaev vs. Strickland · Khamzat Chimaev vs Sean Strickland
  "ed2fa2cd-0896-40e3-9fd3-ef9b33e1377a", // 2026-05-09 · UFC 328: Chimaev vs. Strickland · Joshua Van vs Tatsuro Taira
  "93c107a5-7b18-401c-8271-794b89e41763", // 2026-04-11 · UFC 327: Prochazka vs. Ulberg · Carlos Ulberg vs Jiri Prochazka
  "5aeba8c9-c220-44b3-aed8-3fdd5652b3e3", // 2026-01-31 · UFC 325: Volkanovski vs. Lopes 2 · Alexander Volkanovski vs Diego Lopes
  "d888680c-fa68-47fb-8b9f-35f3b41a27d2", // 2026-01-24 · UFC 324: Gaethje vs. Pimblett · Justin Gaethje vs Paddy Pimblett
  "ecdb40c4-4801-49a8-b39a-9101b376f9ed", // 2025-12-06 · UFC 323: Dvalishvili vs. Yan 2 · Merab Dvalishvili vs Petr Yan
  "d31d490d-2ffb-4ea9-8aaa-f96cce77955d", // 2025-12-06 · UFC 323: Dvalishvili vs. Yan 2 · Alexandre Pantoja vs Joshua Van
  "eab763ca-5d01-4e3e-96db-3af23d4e7330", // 2025-11-15 · UFC 322: Della Maddalena vs. Makhachev · Jack Della Maddalena vs Islam Makhachev
  "5c96e392-0e82-4186-9616-db6e0bcb721d", // 2025-11-15 · UFC 322: Della Maddalena vs. Makhachev · Valentina Shevchenko vs Zhang Weili
  "44eba65e-3aa5-4f83-a716-8b25193e0627", // 2025-10-25 · UFC 321: Aspinall vs. Gane · Tom Aspinall vs Ciryl Gane
  "0f453494-d9db-4c99-8bc0-c00d948e411a", // 2025-10-25 · UFC 321: Aspinall vs. Gane · Mackenzie Dern vs Virna Jandiroba
  "a4bc2812-2ff7-441a-aff0-96bd16a954ae", // 2025-10-04 · UFC 320: Ankalaev vs. Pereira 2 · Magomed Ankalaev vs Alex Pereira
  "03ba29d4-9423-4ede-9abf-16ddeaa4ee83", // 2025-10-04 · UFC 320: Ankalaev vs. Pereira 2 · Merab Dvalishvili vs Cory Sandhagen
  "81ee0fdf-bee0-4911-8c91-9718ef5fa482", // 2025-08-16 · UFC 319: Du Plessis vs. Chimaev · Dricus Du Plessis vs Khamzat Chimaev
  "7dbd3c09-b6cd-447c-bd93-fc4376139eb7", // 2025-06-28 · UFC 317: Topuria vs. Oliveira · Ilia Topuria vs Charles Oliveira
  "af3ddee2-6346-4b57-b65e-76ce38faf376", // 2025-06-28 · UFC 317: Topuria vs. Oliveira · Alexandre Pantoja vs Kai Kara-France
  "887df5eb-11c6-4a5c-9bd0-21193040b9a5", // 2025-06-07 · UFC 316: Dvalishvili vs. O'Malley 2 · Merab Dvalishvili vs Sean O'Malley
  "45ef0f4c-2513-4714-acbf-e2373e57b0e3", // 2025-06-07 · UFC 316: Dvalishvili vs. O'Malley 2 · Julianna Pena vs Kayla Harrison
  "f0039537-02e3-4092-8918-f285612b57c7", // 2025-05-10 · UFC 315: Muhammad vs. Della Maddalena · Belal Muhammad vs Jack Della Maddalena
  "bc22987a-fda3-4c29-aab5-d09542560b1a", // 2025-05-10 · UFC 315: Muhammad vs. Della Maddalena · Valentina Shevchenko vs Manon Fiorot
  "7bd98524-718e-4835-85cc-a5590ec72c79", // 2025-04-12 · UFC 314: Volkanovski vs. Lopes · Alexander Volkanovski vs Diego Lopes
  "46061d6f-04eb-43a4-b34d-0a3bbed957f4", // 2025-03-08 · UFC 313: Pereira vs. Ankalaev · Alex Pereira vs Magomed Ankalaev
  "ecca6af1-f088-4460-8a4c-5e744dbd5b14", // 2025-02-08 · UFC 312: Du Plessis vs. Strickland 2 · Dricus Du Plessis vs Sean Strickland
  "2bf4c511-931f-4474-a41b-762a810b4bd4", // 2025-02-08 · UFC 312: Du Plessis vs. Strickland 2 · Zhang Weili vs Tatiana Suarez
  "4e8868a8-8ac4-456e-8e41-6e086812daa3", // 2025-01-18 · UFC 311: Makhachev vs. Moicano · Islam Makhachev vs Renato Moicano
  "fda6561d-2272-4087-b4f5-96f13dc857d9", // 2025-01-18 · UFC 311: Makhachev vs. Moicano · Merab Dvalishvili vs Umar Nurmagomedov
  "d023b42f-e0b0-445f-a855-0cb37a0c18cf", // 2024-12-07 · UFC 310: Pantoja vs. Asakura · Alexandre Pantoja vs Kai Asakura
  "901d0fcb-b798-482d-a11f-c20ddfc6db1d", // 2024-11-16 · UFC 309: Jones vs. Miocic · Jon Jones vs Stipe Miocic
  "ffc36d5e-4881-4bdf-a8ac-8d7d477aa8a3", // 2024-10-26 · UFC 308: Topuria vs. Holloway · Ilia Topuria vs Max Holloway
  "efd1b690-58ed-4222-af8b-4733f67805fb", // 2024-10-05 · UFC 307: Pereira vs. Rountree Jr. · Alex Pereira vs Khalil Rountree Jr.
  "fc7a7461-cbcf-499b-a077-2879bf1dd304", // 2024-10-05 · UFC 307: Pereira vs. Rountree Jr. · Raquel Pennington vs Julianna Pena
  "dea47513-e078-4a0b-a5bd-fde087325883", // 2024-09-14 · UFC 306: Riyadh Season Noche UFC · Sean O'Malley vs Merab Dvalishvili
  "2fd5e96c-fd44-4046-b071-11fe000de920", // 2024-09-14 · UFC 306: Riyadh Season Noche UFC · Alexa Grasso vs Valentina Shevchenko
  "cef7a11d-37bd-46a4-9f34-1675fd681875", // 2024-08-17 · UFC 305: Du Plessis vs. Adesanya · Dricus Du Plessis vs Israel Adesanya
  "a52a70d9-ff4b-488a-aeb0-2336abb1d552", // 2024-07-27 · UFC 304: Edwards vs. Muhammad 2 · Tom Aspinall vs Curtis Blaydes
  "1c63c3df-7af4-49d4-8ea6-cb44a8d351a1", // 2024-07-27 · UFC 304: Edwards vs. Muhammad 2 · Leon Edwards vs Belal Muhammad
  "00f83584-457a-4aaa-b3e6-a96b81ae147c", // 2024-06-29 · UFC 303: Pereira vs. Prochazka 2 · Alex Pereira vs Jiri Prochazka
  "f1afe409-c54a-4d53-a6c3-bb6536fbdf08", // 2024-06-01 · UFC 302: Makhachev vs. Poirier · Islam Makhachev vs Dustin Poirier
  "4b32b412-d4b0-4121-949d-5b47cef9669d", // 2024-05-04 · UFC 301: Pantoja vs. Erceg · Alexandre Pantoja vs Steve Erceg
  "aa4e5169-392e-4152-ab4d-eaaeda6af2ab", // 2024-04-13 · UFC 300: Pereira vs. Hill · Alex Pereira vs Jamahal Hill
  "d07fe53b-780b-431c-94d6-d17efbf5ff10", // 2024-04-13 · UFC 300: Pereira vs. Hill · Zhang Weili vs Yan Xiaonan
  "ffa833fc-42cc-4679-ab12-1166de48ec3d", // 2024-03-09 · UFC 299: O'Malley vs. Vera 2 · Sean O'Malley vs Marlon Vera
  "cda9db87-acdb-4024-bf0b-289bfad6cb9d", // 2024-02-17 · UFC 298: Volkanovski vs. Topuria · Alexander Volkanovski vs Ilia Topuria
  "9a8affe6-e150-4c2f-a1c7-661055cb8bea", // 2024-01-20 · UFC 297: Strickland vs. Du Plessis · Sean Strickland vs Dricus Du Plessis
  "d00a9693-9d21-4116-970d-e50b4b8ea163", // 2024-01-20 · UFC 297: Strickland vs. Du Plessis · Raquel Pennington vs Mayra Bueno Silva
  "433b018f-3e70-4f9d-98c3-44952709bd41", // 2023-12-16 · UFC 296: Edwards vs. Covington · Leon Edwards vs Colby Covington
  "25fe2137-6e18-40f5-9399-63831a441049", // 2023-12-16 · UFC 296: Edwards vs. Covington · Alexandre Pantoja vs Brandon Royval
  "69d78d34-c429-40bc-a197-baf8fac7a613", // 2023-11-11 · UFC 295: Prochazka vs. Pereira · Tom Aspinall vs Sergei Pavlovich
  "e90ff4cb-495c-4b12-afd6-3a6a2cfc083e", // 2023-11-11 · UFC 295: Prochazka vs. Pereira · Alex Pereira vs Jiri Prochazka
  "8c09c4fd-6408-4cb7-a549-c83de419cb08", // 2023-10-21 · UFC 294: Makhachev vs. Volkanovski 2 · Islam Makhachev vs Alexander Volkanovski
  "2eaba757-6d32-49c1-a8f4-2263c65fbea0", // 2023-09-16 · UFC Fight Night: Grasso vs. Shevchenko 2 · Alexa Grasso vs Valentina Shevchenko
  "d5426913-85e9-4577-a444-445196ad347f", // 2023-09-09 · UFC 293: Adesanya vs. Strickland · Israel Adesanya vs Sean Strickland
  "bf57f5bd-3823-415b-ac5a-d0556421ad80", // 2023-08-19 · UFC 292: Sterling vs. O'Malley · Aljamain Sterling vs Sean O'Malley
  "0b909120-0c18-4ba9-93f0-3c1257524331", // 2023-08-19 · UFC 292: Sterling vs. O'Malley · Zhang Weili vs Amanda Lemos
  "7d69c83c-eab7-4fc3-b94b-bc06d7c7c741", // 2023-07-08 · UFC 290: Volkanovski vs. Rodriguez · Alexander Volkanovski vs Yair Rodriguez
  "6ddeb49f-1b46-4534-90c6-535ce62d29d0", // 2023-07-08 · UFC 290: Volkanovski vs. Rodriguez · Brandon Moreno vs Alexandre Pantoja
  "21447804-cd8e-4deb-8f4d-7a7589a08da3", // 2023-06-10 · UFC 289: Nunes vs. Aldana · Amanda Nunes vs Irene Aldana
  "bf2e9966-63ab-49bf-b287-d55d57bdefde", // 2023-05-06 · UFC 288: Sterling vs. Cejudo · Aljamain Sterling vs Henry Cejudo
  "647e2d30-fd67-4a16-ae20-bf5869595027", // 2023-04-08 · UFC 287: Pereira vs. Adesanya 2 · Alex Pereira vs Israel Adesanya
  "b0a4a716-c88a-46cb-bab0-586de7353517", // 2023-03-18 · UFC 286: Edwards vs. Usman 3 · Leon Edwards vs Kamaru Usman
  "20cf9ba1-ab8b-48fa-9019-c9dd1e1d418b", // 2023-03-04 · UFC 285: Jones vs. Gane · Jon Jones vs Ciryl Gane
  "496b0f44-16d4-470a-adcf-5d3612bb69f4", // 2023-03-04 · UFC 285: Jones vs. Gane · Valentina Shevchenko vs Alexa Grasso
  "14e8e1b7-7737-4356-a231-e88bbed0595c", // 2023-02-11 · UFC 284: Makhachev vs. Volkanovski · Islam Makhachev vs Alexander Volkanovski
  "f59ccb46-994f-448f-aba2-7648f06608ce", // 2023-01-21 · UFC 283: Teixeira vs. Hill · Jamahal Hill vs Glover Teixeira
  "c885ccd5-ef3b-4576-bc25-64d8d1bee595", // 2023-01-21 · UFC 283: Teixeira vs. Hill · Deiveson Figueiredo vs Brandon Moreno
  "0089d23d-8b89-42d7-85b8-034534fe9453", // 2022-11-12 · UFC 281: Adesanya vs. Pereira · Israel Adesanya vs Alex Pereira
  "1c9a2c8c-33bb-4f5c-b653-38c216f0adc5", // 2022-11-12 · UFC 281: Adesanya vs. Pereira · Carla Esparza vs Zhang Weili
  "08bb907b-75fd-4af7-8b95-473941e8483e", // 2022-10-22 · UFC 280: Oliveira vs. Makhachev · Islam Makhachev vs Charles Oliveira
  "b3ddefc0-898b-4527-b910-3c9fa0bbe3fb", // 2022-10-22 · UFC 280: Oliveira vs. Makhachev · Aljamain Sterling vs TJ Dillashaw
  "242c37b6-f1b8-4f5a-88a8-25e58abadf55", // 2022-08-20 · UFC 278: Usman vs. Edwards · Kamaru Usman vs Leon Edwards
  "fa399fec-ba48-4fb0-8665-a9de1f3ddb2d", // 2022-07-30 · UFC 277: Pena vs. Nunes 2 · Brandon Moreno vs Kai Kara-France
  "a55bcbb5-f4fa-4742-8f49-9365c998dc1b", // 2022-07-30 · UFC 277: Pena vs. Nunes 2 · Julianna Pena vs Amanda Nunes
  "01bb914d-f42e-4a6f-9caf-7f21e4c915c1", // 2022-07-02 · UFC 276: Adesanya vs. Cannonier · Israel Adesanya vs Jared Cannonier
  "a9315097-35b4-42a6-91cc-76393e9db057", // 2022-07-02 · UFC 276: Adesanya vs. Cannonier · Alexander Volkanovski vs Max Holloway
  "13dfdf5a-d853-43ef-9f3f-18bd1608db9e", // 2022-06-11 · UFC 275: Teixeira vs. Prochazka · Glover Teixeira vs Jiri Prochazka
  "0c5ee48b-ca9e-4d73-9e56-c8bc0d670986", // 2022-06-11 · UFC 275: Teixeira vs. Prochazka · Valentina Shevchenko vs Taila Santos
  "43d29794-9d1d-45cc-ba65-59f977796a73", // 2022-05-07 · UFC 274: Oliveira vs. Gaethje · Rose Namajunas vs Carla Esparza
  "69d811ca-72f4-46b0-9540-ff4689e2a339", // 2022-04-09 · UFC 273: Volkanovski vs. The Korean Zombie · Alexander Volkanovski vs Chan Sung Jung
  "111ccda1-42f7-45f1-b2ec-814fdff1904e", // 2022-04-09 · UFC 273: Volkanovski vs. The Korean Zombie · Petr Yan vs Aljamain Sterling
  "7fc11f68-361d-4cbb-be43-dafcbf2a3e62", // 2022-02-12 · UFC 271: Adesanya vs. Whittaker 2 · Israel Adesanya vs Robert Whittaker
  "0b01f17c-5e43-4cb0-8bf4-7771d7017485", // 2022-01-22 · UFC 270: Ngannou vs. Gane · Francis Ngannou vs Ciryl Gane
  "872396b7-cbd7-4491-915e-985a91aa3241", // 2022-01-22 · UFC 270: Ngannou vs. Gane · Brandon Moreno vs Deiveson Figueiredo
  "4179feb6-1f88-4657-8bf9-829219cc06a6", // 2021-12-11 · UFC 269: Oliveira vs. Poirier · Charles Oliveira vs Dustin Poirier
  "8b16e6dc-6ff6-4c1f-b362-b3f503c8dd72", // 2021-12-11 · UFC 269: Oliveira vs. Poirier · Amanda Nunes vs Julianna Pena
  "792bd1fd-1b10-431b-9277-a0c57176cc61", // 2021-11-06 · UFC 268: Usman vs. Covington 2 · Kamaru Usman vs Colby Covington
  "872fbf04-703e-4f98-8572-f763380e4539", // 2021-11-06 · UFC 268: Usman vs. Covington 2 · Rose Namajunas vs Zhang Weili
  "065209d2-f982-42d5-ab98-e89e80a72d5b", // 2021-10-30 · UFC 267: Blachowicz vs. Teixeira · Jan Blachowicz vs Glover Teixeira
  "60d4b96e-3efd-4fdb-8089-ca5a42667b46", // 2021-10-30 · UFC 267: Blachowicz vs. Teixeira · Petr Yan vs Cory Sandhagen
  "97989a11-4ba7-41ab-9fca-b0798ae8988a", // 2021-09-25 · UFC 266: Volkanovski vs. Ortega · Alexander Volkanovski vs Brian Ortega
  "434ff80a-21f9-434b-9de3-ed7dd388979b", // 2021-09-25 · UFC 266: Volkanovski vs. Ortega · Valentina Shevchenko vs Lauren Murphy
  "dd7afe4a-d6cd-4d7a-8ddc-cad9b1647489", // 2021-08-07 · UFC 265: Lewis vs. Gane · Ciryl Gane vs Derrick Lewis
  "81224429-98b7-45d1-9a89-c6f72d9a9155", // 2021-06-12 · UFC 263: Adesanya vs. Vettori 2 · Israel Adesanya vs Marvin Vettori
  "a1cb52af-447a-4c51-8d53-acdae306c4c8", // 2021-06-12 · UFC 263: Adesanya vs. Vettori 2 · Deiveson Figueiredo vs Brandon Moreno
  "abc01963-3198-4a14-a2c1-e880bcf39fc3", // 2021-05-15 · UFC 262: Oliveira vs. Chandler · Charles Oliveira vs Michael Chandler
  "1dc5a51a-65c1-450c-b7ed-8f4607dd47b4", // 2021-04-24 · UFC 261: Usman vs. Masvidal 2 · Kamaru Usman vs Jorge Masvidal
  "20abdf73-40b6-48be-9f9e-84aeb2a938f4", // 2021-04-24 · UFC 261: Usman vs. Masvidal 2 · Valentina Shevchenko vs Jessica Andrade
  "98b29a87-e099-45b9-88e9-3e3470a0dac5", // 2021-04-24 · UFC 261: Usman vs. Masvidal 2 · Zhang Weili vs Rose Namajunas
  "9a3fbfbc-4adc-45ce-b115-8e0b69b8480b", // 2021-03-27 · UFC 260: Miocic vs. Ngannou · Stipe Miocic vs Francis Ngannou
  "4fc40d68-002c-4de9-b9c3-a4e68b17ff69", // 2021-03-06 · UFC 259: Blachowicz vs. Adesanya · Jan Blachowicz vs Israel Adesanya
  "ff18ce2c-f87a-4b43-8075-87b1cd0c5fd9", // 2021-03-06 · UFC 259: Blachowicz vs. Adesanya · Petr Yan vs Aljamain Sterling
  "302d7626-1736-4777-b6bc-0f808720d808", // 2021-03-06 · UFC 259: Blachowicz vs. Adesanya · Amanda Nunes vs Megan Anderson
  "f0c4b211-e583-4206-81d9-84e650318e8c", // 2021-02-13 · UFC 258: Usman vs. Burns · Kamaru Usman vs Gilbert Burns
  "e63793e6-2993-4168-9a1d-95c4ea30c06a", // 2020-12-12 · UFC 256: Figueiredo vs. Moreno · Deiveson Figueiredo vs Brandon Moreno
  "f5be6bf1-9799-4623-a2e0-f58654ea042d", // 2020-11-21 · UFC 255: Figueiredo vs. Perez · Deiveson Figueiredo vs Alex Perez
  "7030b5b8-4115-4b30-8415-027d42d2654a", // 2020-11-21 · UFC 255: Figueiredo vs. Perez · Valentina Shevchenko vs Jennifer Maia
  "402e6b67-5e1c-4131-9ab4-2740e2267968", // 2020-10-24 · UFC 254: Khabib vs. Gaethje · Justin Gaethje vs Khabib Nurmagomedov
  "6fedd96f-44ae-40b9-a47e-23900be203a9", // 2020-09-26 · UFC 253: Adesanya vs. Costa · Jan Blachowicz vs Dominick Reyes
  "d4de2e15-6179-48f0-a627-d6bd71f5a772", // 2020-09-26 · UFC 253: Adesanya vs. Costa · Israel Adesanya vs Paulo Costa
  "1e17ea53-63f0-4a44-b644-79183c926294", // 2020-08-15 · UFC 252: Miocic vs. Cormier 3 · Stipe Miocic vs Daniel Cormier
  "efc6abee-2fe3-4393-adc2-5d3c30a873c1", // 2020-07-18 · UFC Fight Night: Figueiredo vs. Benavidez 2 · Deiveson Figueiredo vs Joseph Benavidez
  "9e21173a-933b-4f87-81d5-61ec7457cc1b", // 2020-07-11 · UFC 251: Usman vs. Masvidal · Kamaru Usman vs Jorge Masvidal
  "ca0c6474-464e-4f5e-b858-e0b6de8fe490", // 2020-07-11 · UFC 251: Usman vs. Masvidal · Alexander Volkanovski vs Max Holloway
  "80777d32-78d7-46cb-96e1-84cad63096a7", // 2020-07-11 · UFC 251: Usman vs. Masvidal · Petr Yan vs Jose Aldo
  "01e069f4-1bdc-4c21-9d3e-8d21713e4e36", // 2020-06-06 · UFC 250: Nunes vs. Spencer · Amanda Nunes vs Felicia Spencer
  "6c338ca8-0c05-4e7d-bf92-b9291bd4c584", // 2020-05-09 · UFC 249: Ferguson vs. Gaethje · Justin Gaethje vs Tony Ferguson
  "27087493-f8ac-470a-8950-6c80c0d84bcd", // 2020-05-09 · UFC 249: Ferguson vs. Gaethje · Henry Cejudo vs Dominick Cruz
  "3c15b87f-a49f-45ff-852b-2b58611dbd20", // 2020-03-07 · UFC 248: Adesanya vs. Romero · Israel Adesanya vs Yoel Romero
  "649a95e2-8246-46d0-8fa4-49c65da85911", // 2020-03-07 · UFC 248: Adesanya vs. Romero · Zhang Weili vs Joanna Jedrzejczyk
  "eca02987-52a5-4f91-aa94-e46c2d932a9d", // 2020-02-29 · UFC Fight Night: Benavidez vs. Figueiredo · Joseph Benavidez vs Deiveson Figueiredo
  "d50651d3-d1f4-4edb-b04f-b6703647c1ae", // 2020-02-08 · UFC 247: Jones vs. Reyes · Jon Jones vs Dominick Reyes
  "9c8e15af-08ff-45cb-a7cb-9a599a156045", // 2020-02-08 · UFC 247: Jones vs. Reyes · Valentina Shevchenko vs Katlyn Cerminara
  "8a702bc4-2cce-464f-9524-45bd9da84156", // 2019-12-14 · UFC 245: Usman vs. Covington · Kamaru Usman vs Colby Covington
  "4e081b72-0bff-4f1d-85fc-214ad7389246", // 2019-12-14 · UFC 245: Usman vs. Covington · Max Holloway vs Alexander Volkanovski
  "6a489333-5a29-4756-bb21-6a1bdf32f205", // 2019-12-14 · UFC 245: Usman vs. Covington · Amanda Nunes vs Germaine de Randamie
  "cda4f7d5-bcf7-4857-bb23-c4fb9198030c", // 2019-10-05 · UFC 243: Whittaker vs. Adesanya · Robert Whittaker vs Israel Adesanya
  "4e0a3273-adf7-45f1-9f92-dc09187c29e7", // 2019-09-07 · UFC 242: Khabib vs. Poirier · Dustin Poirier vs Khabib Nurmagomedov
  "1d0e8f8a-9624-4af7-b8f1-71a70f42bbd6", // 2019-08-31 · UFC Fight Night: Andrade vs. Zhang · Jessica Andrade vs Zhang Weili
  "f958c971-28df-4b2b-acde-1ccfe0a6a7fe", // 2019-08-17 · UFC 241: Cormier vs. Miocic 2 · Daniel Cormier vs Stipe Miocic
  "7d1c03d3-62ea-4e63-acef-6e50fa835904", // 2019-08-10 · UFC Fight Night: Shevchenko vs. Carmouche 2 · Valentina Shevchenko vs Liz Carmouche
  "b9b4532d-c372-49dd-b5ff-854d162c7bca", // 2019-07-27 · UFC 240: Holloway vs. Edgar · Max Holloway vs Frankie Edgar
  "c286ba57-3439-4ac7-a019-5e19effc3721", // 2019-07-06 · UFC 239: Jones vs. Santos · Jon Jones vs Thiago Santos
  "31f293c8-473d-4bcf-aaf8-bceaf8b2b7ca", // 2019-07-06 · UFC 239: Jones vs. Santos · Amanda Nunes vs Holly Holm
  "e518d397-ca6d-445c-b07e-6909e7459776", // 2019-06-08 · UFC 238: Cejudo vs. Moraes · Henry Cejudo vs Marlon Moraes
  "34c78393-0c94-416b-bbca-065bec1f533b", // 2019-06-08 · UFC 238: Cejudo vs. Moraes · Valentina Shevchenko vs Jessica Eye
  "d8887941-b6d5-4186-bdad-bf722a83f350", // 2019-05-11 · UFC 237: Namajunas vs. Andrade · Rose Namajunas vs Jessica Andrade
  "cbdd6f5c-f450-4d00-baac-9ff732996559", // 2019-04-13 · UFC 236: Holloway vs. Poirier 2 · Israel Adesanya vs Kelvin Gastelum
  "9fd25745-4557-41aa-944c-c6bf73dea9f9", // 2019-04-13 · UFC 236: Holloway vs. Poirier 2 · Dustin Poirier vs Max Holloway
  "cedcd2a5-d5d4-4707-bc4d-e31260a12ed6", // 2019-03-02 · UFC 235: Jones vs. Smith · Jon Jones vs Anthony Smith
  "9c81f8db-a76d-4f04-8119-7a705f432254", // 2019-03-02 · UFC 235: Jones vs. Smith · Tyron Woodley vs Kamaru Usman
  "f6f139e3-be17-4ac6-bbac-c5ddd0527377", // 2019-01-19 · UFC Fight Night: Cejudo vs. Dillashaw · Henry Cejudo vs TJ Dillashaw
  "ec38efcc-3c21-487e-9d78-23d6820771ad", // 2018-12-29 · UFC 232: Jones vs. Gustafsson 2 · Jon Jones vs Alexander Gustafsson
  "cca69b12-493a-46fa-938e-f9072838f0c5", // 2018-12-29 · UFC 232: Jones vs. Gustafsson 2 · Cristiane Justino vs Amanda Nunes
  "f792a1bb-9fa7-4ec8-9804-a1ccdbda6ea0", // 2018-12-08 · UFC 231: Holloway vs. Ortega · Max Holloway vs Brian Ortega
  "eb34edb9-bbef-45bf-a713-92ba0705b014", // 2018-12-08 · UFC 231: Holloway vs. Ortega · Valentina Shevchenko vs Joanna Jedrzejczyk
  "6e5b0e88-1974-4a84-8b29-2e8ac05759ed", // 2018-11-03 · UFC 230: Cormier vs. Lewis · Daniel Cormier vs Derrick Lewis
  "d97e76c9-4afe-4bb2-9f36-b01e67b02c10", // 2018-10-06 · UFC 229: Khabib vs. McGregor · Khabib Nurmagomedov vs Conor McGregor
  "b9b19c9e-5736-430b-87be-855f49f6fe6e", // 2018-09-08 · UFC 228: Woodley vs. Till · Tyron Woodley vs Darren Till
  "9de4f46f-81f4-4545-acc3-d0df0275858c", // 2018-08-04 · UFC 227: Dillashaw vs. Garbrandt 2 · TJ Dillashaw vs Cody Garbrandt
  "26b88b3b-df1a-47ad-af07-29ef492ab6a7", // 2018-08-04 · UFC 227: Dillashaw vs. Garbrandt 2 · Demetrious Johnson vs Henry Cejudo
  "d1a9e22e-1e87-41d3-9191-eb0e12118d38", // 2018-07-07 · UFC 226: Miocic vs. Cormier · Stipe Miocic vs Daniel Cormier
  "56e4ca42-fbc4-4f09-ad7d-b08dfb447429", // 2018-06-09 · UFC 225: Whittaker vs. Romero 2 · Robert Whittaker vs Yoel Romero
  "e78ad6ef-693b-4412-8b31-5202e0641afb", // 2018-06-09 · UFC 225: Whittaker vs. Romero 2 · Colby Covington vs Rafael Dos Anjos
  "4521828c-2aa8-40c7-9c70-9775dbbf3840", // 2018-05-12 · UFC 224: Nunes vs. Pennington · Amanda Nunes vs Raquel Pennington
  "ab636be2-a353-4abf-9844-22a268629366", // 2018-04-07 · UFC 223: Khabib vs. Iaquinta · Khabib Nurmagomedov vs Al Iaquinta
  "d59116c8-75bd-4e5b-9d66-99e823d52448", // 2018-04-07 · UFC 223: Khabib vs. Iaquinta · Rose Namajunas vs Joanna Jedrzejczyk
  "ae81e13d-b48f-4dcd-b0b1-6696dcaff3bd", // 2018-03-03 · UFC 222: Cyborg vs. Kunitskaya · Cristiane Justino vs Yana Santos
  "aa1c065f-bc03-40e0-8698-f184fa2ca27e", // 2018-01-20 · UFC 220: Miocic vs. Ngannou · Stipe Miocic vs Francis Ngannou
  "d17f745a-69cb-487e-896f-c4a3e8054704", // 2018-01-20 · UFC 220: Miocic vs. Ngannou · Daniel Cormier vs Volkan Oezdemir
  "a437d892-3ae9-40b4-b2c7-5d8a5ee20fbe", // 2017-12-30 · UFC 219: Cyborg vs. Holm · Cristiane Justino vs Holly Holm
  "561b2dbc-e513-4c49-bfe4-3c1cc7a817a5", // 2017-12-02 · UFC 218: Holloway vs. Aldo 2 · Max Holloway vs Jose Aldo
  "51cc3bba-fa1f-4128-bf2e-ebe39334c104", // 2017-12-01 · The Ultimate Fighter: A New World Champion Finale · Nicco Montano vs Roxanne Modafferi
  "ad540294-6889-4e2d-acb6-e4396d6179ab", // 2017-11-04 · UFC 217: Bisping vs. St-Pierre · Michael Bisping vs Georges St-Pierre
  "2524f6b1-011f-4199-81d0-e8026461341a", // 2017-11-04 · UFC 217: Bisping vs. St-Pierre · Cody Garbrandt vs TJ Dillashaw
  "6b0897fd-70f1-411c-a681-5c8c2ce223c8", // 2017-11-04 · UFC 217: Bisping vs. St-Pierre · Joanna Jedrzejczyk vs Rose Namajunas
  "dd3f9227-3c71-45fa-bc9b-05546f0a3df9", // 2017-10-07 · UFC 216: Ferguson vs. Lee · Tony Ferguson vs Kevin Lee
  "3aac7198-8298-468c-8783-1980cce8976f", // 2017-10-07 · UFC 216: Ferguson vs. Lee · Demetrious Johnson vs Ray Borg
  "bae7660c-cbae-4a05-9a38-d4e1f2b06a4f", // 2017-09-09 · UFC 215: Nunes vs Shevchenko 2 · Amanda Nunes vs Valentina Shevchenko
  "c0aaa1af-9ecc-4dba-a83b-d20e37473ec7", // 2017-07-29 · UFC 214: Cormier vs. Jones 2 · Daniel Cormier vs Jon Jones
  "0a85714f-d76a-4f72-bfb8-ff15a0078745", // 2017-07-29 · UFC 214: Cormier vs. Jones 2 · Tyron Woodley vs Demian Maia
  "de9b702f-2d9c-4972-9e70-3df281ef8de7", // 2017-07-29 · UFC 214: Cormier vs. Jones 2 · Cristiane Justino vs Tonya Evinger
  "5efb55f9-c70f-485a-88e5-5d4838ec6630", // 2017-07-08 · UFC 213: Romero vs. Whittaker · Robert Whittaker vs Yoel Romero
  "9d67c8b2-cb4a-41e8-8a3e-1abba2823cad", // 2017-06-03 · UFC 212: Aldo vs. Holloway · Max Holloway vs Jose Aldo
  "595f4e9b-151d-49bd-b58d-8e727c5bd61c", // 2017-05-13 · UFC 211: Miocic vs. Dos Santos · Stipe Miocic vs Junior Dos Santos
  "edb7466a-cd3d-48b8-b822-1fd708ec74aa", // 2017-05-13 · UFC 211: Miocic vs. Dos Santos · Joanna Jedrzejczyk vs Jessica Andrade
  "b058b2db-9809-40d1-9d56-37f2ce297950", // 2017-04-15 · UFC on FOX: Johnson vs. Reis · Demetrious Johnson vs Wilson Reis
  "90967d2d-5708-4026-bcd0-321421bbd064", // 2017-04-08 · UFC 210: Cormier vs. Johnson 2 · Daniel Cormier vs Anthony Johnson
  "f0517cf4-dfa5-4758-88d3-b68c6cf0aa2c", // 2017-03-04 · UFC 209: Woodley vs. Thompson 2 · Tyron Woodley vs Stephen Thompson
  "fb416162-4d98-4174-a23b-a46bbf68186d", // 2017-02-11 · UFC 208: Holm vs. De Randamie · Germaine de Randamie vs Holly Holm
  "13c798e4-720f-4595-83f1-bf253c5aacd7", // 2016-12-30 · UFC 207: Nunes vs. Rousey · Dominick Cruz vs Cody Garbrandt
  "39a4c56b-6d8e-456f-bd49-cb86ada52870", // 2016-12-30 · UFC 207: Nunes vs. Rousey · Amanda Nunes vs Ronda Rousey
  "e3704ede-f982-492d-99dc-a00c3f98ee31", // 2016-12-10 · UFC 206: Holloway vs. Pettis · Max Holloway vs Anthony Pettis
  "fe369cbb-5d85-4ba2-859f-ae03f562e682", // 2016-12-03 · The Ultimate Fighter: Tournament of Champions Finale · Demetrious Johnson vs Tim Elliott
  "c22ef5cd-a647-45c7-94fc-635da620c2b0", // 2016-11-12 · UFC 205: Alvarez vs McGregor · Tyron Woodley vs Stephen Thompson
  "f3990995-bb6d-4dbe-9650-3d090d9c42dd", // 2016-11-12 · UFC 205: Alvarez vs McGregor · Eddie Alvarez vs Conor McGregor
  "3f53b33f-8ae3-4182-baa9-dd5932d81a03", // 2016-11-12 · UFC 205: Alvarez vs McGregor · Joanna Jedrzejczyk vs Karolina Kowalkiewicz
  "f55f2019-330c-4080-9180-c877ef8afa67", // 2016-10-08 · UFC 204: Bisping vs. Henderson · Michael Bisping vs Dan Henderson
  "9ed3e7d3-41bc-4fa1-b952-f7d2f658d69e", // 2016-09-10 · UFC 203: Miocic vs. Overeem · Stipe Miocic vs Alistair Overeem
  "075df8cb-ce80-438c-8f92-d1d8e08ba159", // 2016-07-30 · UFC 201: Lawler vs. Woodley · Robbie Lawler vs Tyron Woodley
  "1ef6ea0c-c766-4056-bc17-1fe31c071c0f", // 2016-07-09 · UFC 200: Tate vs Nunes · Daniel Cormier vs Anderson Silva
  "a8551a8d-f0d0-4c47-ab8d-05a72ccfc41f", // 2016-07-09 · UFC 200: Tate vs Nunes · Jose Aldo vs Frankie Edgar
  "a9ab8690-16a0-4552-825c-7567bb6d7e96", // 2016-07-09 · UFC 200: Tate vs Nunes · Miesha Tate vs Amanda Nunes
  "d0ce3887-ffe0-4134-ab38-12a529779fde", // 2016-07-08 · The Ultimate Fighter: Team Joanna vs. Team Cláudia Finale · Joanna Jedrzejczyk vs Claudia Gadelha
  "9b2f5397-b0dc-4a3b-8f9f-5ef3eb494aea", // 2016-07-07 · UFC Fight Night: Dos Anjos vs. Alvarez · Rafael Dos Anjos vs Eddie Alvarez
  "3a2a660b-d81f-4ee6-91a3-aa255b2d676a", // 2016-06-04 · UFC 199: Rockhold vs. Bisping 2 · Luke Rockhold vs Michael Bisping
  "0e0dde20-82f2-4bd2-9b6c-9632332e10bf", // 2016-06-04 · UFC 199: Rockhold vs. Bisping 2 · Dominick Cruz vs Urijah Faber
  "f479a2e5-6eaa-468c-bd8c-ebc13a0df549", // 2016-05-14 · UFC 198: Werdum vs Miocic · Fabricio Werdum vs Stipe Miocic
  "ad7fd325-86d1-4536-a609-4a576c1fc54e", // 2016-04-23 · UFC 197: Jones vs Saint Preux · Jon Jones vs Ovince Saint Preux
  "abeee5b9-a0b0-4254-9d18-39fd7c1afec4", // 2016-04-23 · UFC 197: Jones vs Saint Preux · Demetrious Johnson vs Henry Cejudo
  "fed84909-4f5a-4eb5-8ac6-3b71af1f1f32", // 2016-03-05 · UFC 196: McGregor vs Diaz · Holly Holm vs Miesha Tate
  "f8d2b184-050e-45e5-afc5-4a4b476437be", // 2016-01-17 · UFC Fight Night: Dillashaw vs Cruz · TJ Dillashaw vs Dominick Cruz
  "2370b147-365f-4021-845e-06e2f7d1ab3b", // 2016-01-02 · UFC 195: Lawler vs Condit · Robbie Lawler vs Carlos Condit
  "837e76b5-b4e8-4f35-a1a0-bcbc663f364d", // 2015-12-19 · UFC on FOX: Dos Anjos vs. Cowboy 2 · Rafael Dos Anjos vs Donald Cerrone
  "b09a24c6-85eb-427c-88cb-85b8a3ecb821", // 2015-12-12 · UFC 194: Aldo vs McGregor · Chris Weidman vs Luke Rockhold
  "9c9613d3-6171-4164-99f2-461b1d6d7c90", // 2015-12-12 · UFC 194: Aldo vs McGregor · Jose Aldo vs Conor McGregor
  "777d6b35-eb53-4948-9ee3-891b8522ae66", // 2015-11-14 · UFC 193: Rousey vs Holm · Ronda Rousey vs Holly Holm
  "c7269b5e-5ebb-4ade-84b4-5e03a5c35aec", // 2015-11-14 · UFC 193: Rousey vs Holm · Joanna Jedrzejczyk vs Valerie Letourneau
  "a797035a-13c5-4fbf-9809-6837e0d18218", // 2015-10-03 · UFC 192: Cormier vs Gustafsson · Daniel Cormier vs Alexander Gustafsson
  "14905c01-d9cd-4def-a358-18c374ac5e4b", // 2015-09-05 · UFC 191: Johnson vs Dodson 2 · Demetrious Johnson vs John Dodson
  "7c48be48-d417-4743-a12f-119f5b89d0c9", // 2015-08-01 · UFC 190: Rousey vs Correia · Ronda Rousey vs Bethe Correia
  "56e0e50a-f990-4b21-9ccf-ff1ba1b7487e", // 2015-07-25 · UFC on FOX: Dillashaw vs. Barao II · TJ Dillashaw vs Renan Barao
  "b88815af-6d92-442f-9698-cd84df955352", // 2015-07-11 · UFC 189: Mendes vs McGregor · Robbie Lawler vs Rory MacDonald
  "aa6cde41-14d1-4584-ba33-e020b4994935", // 2015-07-11 · UFC 189: Mendes vs McGregor · Conor McGregor vs Chad Mendes
  "904271d1-066a-4676-b52b-16433db50dd4", // 2015-06-20 · UFC Fight Night: Jedrzejczyk vs Penne · Joanna Jedrzejczyk vs Jessica Penne
  "b035f3ac-88f6-4841-b3a9-9a84d7ca3e88", // 2015-06-13 · UFC 188: Velasquez vs Werdum · Cain Velasquez vs Fabricio Werdum
  "09b2fdc9-7f00-4a9b-ad71-a92d0a9c3296", // 2015-05-23 · UFC 187: Johnson vs Cormier · Daniel Cormier vs Anthony Johnson
  "070fe7a1-47f6-47ca-8aad-a0f62c40ee72", // 2015-05-23 · UFC 187: Johnson vs Cormier · Chris Weidman vs Vitor Belfort
  "c690eb62-63d0-42f9-9e67-20b9b4702568", // 2015-04-25 · UFC 186: Johnson vs Horiguchi · Demetrious Johnson vs Kyoji Horiguchi
  "b8193c2d-cacc-42e6-a0bb-ee1243035e46", // 2015-03-14 · UFC 185: Pettis vs Dos Anjos · Anthony Pettis vs Rafael Dos Anjos
  "e9e18c86-e778-4725-9aa1-40a7999368b5", // 2015-03-14 · UFC 185: Pettis vs Dos Anjos · Carla Esparza vs Joanna Jedrzejczyk
  "11afcc5f-9aa0-4cf3-b7e5-e53ec884fd9b", // 2015-02-28 · UFC 184: Rousey vs Zingano · Ronda Rousey vs Cat Zingano
  "01f193ad-9df0-4e8e-83c4-0c294a1ff9f3", // 2015-01-03 · UFC 182: Jones vs Cormier · Jon Jones vs Daniel Cormier
  "92ddba48-288d-49f0-901c-7396ed0f9487", // 2014-12-12 · The Ultimate Fighter: A Champion Will Be Crowned Finale · Carla Esparza vs Rose Namajunas
  "d983a835-8c5e-40ff-8070-742a92738db0", // 2014-12-06 · UFC 181: Hendricks vs Lawler II · Johny Hendricks vs Robbie Lawler
  "d80c400c-cac4-4a63-b1e2-9001a2104d6b", // 2014-12-06 · UFC 181: Hendricks vs Lawler II · Anthony Pettis vs Gilbert Melendez
  "0e6bb0b0-cc58-4ba2-9a8a-bfe05ded821b", // 2014-11-15 · UFC 180: Werdum vs Hunt · Fabricio Werdum vs Mark Hunt
  "ca352025-b3c1-4ac4-8f55-02e63b609b41", // 2014-10-25 · UFC 179: Aldo vs Mendes 2 · Jose Aldo vs Chad Mendes
  "aeb852cb-c218-497a-a6b6-8eb860bf990d", // 2014-09-27 · UFC 178: Johnson vs Cariaso · Demetrious Johnson vs Chris Cariaso
  "e6007514-fb08-411a-bb07-3388eb710e39", // 2014-08-30 · UFC 177: Dillashaw vs Soto · TJ Dillashaw vs Joe Soto
  "61e44f34-4951-42ec-a637-f8ea71dfd83f", // 2014-07-05 · UFC 175: Weidman vs Machida · Chris Weidman vs Lyoto Machida
  "a2abe490-a123-4b33-b931-7ec0a03ddf5a", // 2014-07-05 · UFC 175: Weidman vs Machida · Ronda Rousey vs Alexis Davis
  "6b3356ae-fc7f-4f2f-b631-0fed34bc969e", // 2014-06-14 · UFC 174: Johnson vs Bagautinov · Demetrious Johnson vs Ali Bagautinov
  "4ae62fbc-75f4-4e91-a4bd-3ac4d1c75057", // 2014-05-24 · UFC 173: Barao vs Dillashaw · Renan Barao vs TJ Dillashaw
  "02483fcd-6473-4a46-9f31-54369ecdf402", // 2014-04-26 · UFC 172: Jones vs Teixeira · Jon Jones vs Glover Teixeira
  "7a6668eb-106d-44b9-bb87-41ac8a2e547f", // 2014-03-15 · UFC 171: Hendricks vs Lawler · Johny Hendricks vs Robbie Lawler
  "dd5465c7-be1c-4f37-a4a1-b34e653f074e", // 2014-02-22 · UFC 170: Rousey vs McMann · Ronda Rousey vs Sara McMann
  "3afeb6ca-472a-43da-b12c-73680fd6a1f1", // 2014-02-01 · UFC 169: Barao vs Faber 2 · Jose Aldo vs Ricardo Lamas
  "cdda8df4-1d3e-4234-b9ce-2652da0d6da7", // 2014-02-01 · UFC 169: Barao vs Faber 2 · Renan Barao vs Urijah Faber
  "b2c30485-364b-4d1d-bddf-008d23936641", // 2013-12-28 · UFC 168: Weidman vs Silva 2 · Chris Weidman vs Anderson Silva
  "566b455c-6a30-4969-bbdf-47337d12d0d2", // 2013-12-28 · UFC 168: Weidman vs Silva 2 · Ronda Rousey vs Miesha Tate
  "9cab4230-b861-4a2d-93ac-f95c5c8bfde2", // 2013-12-14 · UFC on FOX: Johnson vs. Benavidez 2 · Demetrious Johnson vs Joseph Benavidez
  "145b251c-42ac-468f-b933-c6fe828bcb26", // 2013-11-16 · UFC 167: St-Pierre vs Hendricks · Georges St-Pierre vs Johny Hendricks
  "19476fbb-d3b3-4ebe-92d8-80684e54b2dd", // 2013-10-19 · UFC 166: Velasquez vs Dos Santos 3 · Cain Velasquez vs Junior Dos Santos
  "0c167492-1af3-4fd1-84ef-9b99ce3ce725", // 2013-09-21 · UFC 165: Jones vs Gustafsson · Jon Jones vs Alexander Gustafsson
  "24a2b420-8348-4221-b74b-a22f12e18282", // 2013-09-21 · UFC 165: Jones vs Gustafsson · Renan Barao vs Eddie Wineland
  "7b54b0bb-bebf-403b-8fb0-302b42aa7de5", // 2013-08-31 · UFC 164: Henderson vs Pettis 2 · Benson Henderson vs Anthony Pettis
  "e7c271c5-2040-4177-bfa6-7e3c4a8d0c68", // 2013-08-03 · UFC 163: Aldo vs Jung · Jose Aldo vs Chan Sung Jung
  "8de4b7e9-f1e4-4a22-a2b6-b4348ab37307", // 2013-07-27 · UFC on FOX: Johnson vs Moraga · Demetrious Johnson vs John Moraga
  "1d83f335-eb95-4e4c-9930-c83f76c8edfb", // 2013-07-06 · UFC 162: Silva vs Weidman · Anderson Silva vs Chris Weidman
  "4e69684a-adeb-40cf-ad63-03afc5a703b1", // 2013-05-25 · UFC 160: Velasquez vs Silva 2 · Cain Velasquez vs Antonio Silva
  "27cee30d-deaf-451c-b0a8-27aa2061619a", // 2013-04-27 · UFC 159: Jones vs Sonnen · Jon Jones vs Chael Sonnen
  "ca21e349-805d-4024-a68d-dd9ad7900c9e", // 2013-04-20 · UFC on FOX: Henderson vs Melendez · Benson Henderson vs Gilbert Melendez
  "a3b63f03-5b49-454a-a2f6-ffd91aedeb87", // 2013-03-16 · UFC 158: St-Pierre vs Diaz · Georges St-Pierre vs Nick Diaz
  "0df95cbc-e81a-4137-aeb4-5054ea15aa1a", // 2013-02-23 · UFC 157: Rousey vs Carmouche · Ronda Rousey vs Liz Carmouche
  "7b6b8031-8b05-49e0-aa56-806a38fc9c61", // 2013-02-16 · UFC on FUEL TV: Barao vs McDonald · Renan Barao vs Michael McDonald
  "f35af199-56fd-4327-8fba-5ec6fbd5f833", // 2013-02-02 · UFC 156: Aldo vs Edgar · Jose Aldo vs Frankie Edgar
  "d9106c5f-0a37-4087-a1ee-466f190cc5f8", // 2013-01-26 · UFC on FOX: Johnson vs Dodson · Demetrious Johnson vs John Dodson
  "202d802a-e956-448d-afab-41d42af37d77", // 2012-12-29 · UFC 155: Dos Santos vs Velasquez II · Junior Dos Santos vs Cain Velasquez
  "f19c308d-c276-493d-83a9-ced8d7de0520", // 2012-12-08 · UFC on FOX: Henderson vs Diaz · Benson Henderson vs Nate Diaz
  "50659696-db17-47e9-9d42-d6c5e7630993", // 2012-11-17 · UFC 154: St-Pierre vs Condit · Georges St-Pierre vs Carlos Condit
  "f5180c27-45aa-40fd-afa8-3705a70c1e8d", // 2012-09-22 · UFC 152: Jones vs Belfort · Jon Jones vs Vitor Belfort
  "f04f67a1-f80a-47aa-953e-73e5e6d2775d", // 2012-09-22 · UFC 152: Jones vs Belfort · Demetrious Johnson vs Joseph Benavidez
  "9153fed5-088e-48bc-9bb0-70f2c1477ca2", // 2012-08-11 · UFC 150: Henderson vs Edgar II · Benson Henderson vs Frankie Edgar
  "6be4d62e-139d-4a15-bae9-7d4c9732ac54", // 2012-07-21 · UFC 149: Faber vs Barao · Renan Barao vs Urijah Faber
  "7bfbdc3d-f827-4c53-808c-f39c0ba0e960", // 2012-07-07 · UFC 148: Silva vs Sonnen 2 · Anderson Silva vs Chael Sonnen
  "14bb9679-aa26-4e63-a755-04f2da40d0f5", // 2012-05-26 · UFC 146: Dos Santos vs Mir · Junior Dos Santos vs Frank Mir
  "a570e743-3982-45c9-a7f4-40fcb1dac749", // 2012-04-21 · UFC 145: Jones vs Evans · Jon Jones vs Rashad Evans
  "5a366340-a6ac-45d3-af84-8ec10cfa367d", // 2012-02-25 · UFC 144: Edgar vs Henderson · Frankie Edgar vs Benson Henderson
  "207ec239-fb00-46d2-8eaf-12aa4d71ad13", // 2012-02-04 · UFC 143: Diaz vs Condit · Carlos Condit vs Nick Diaz
  "05e24026-0d61-41cc-bf06-d3d32d4793f8", // 2012-01-14 · UFC 142: Aldo vs Mendes · Jose Aldo vs Chad Mendes
  "7f6787cf-878c-4a4b-b7d3-2147e090358b", // 2011-12-10 · UFC 140: Jones vs Machida · Jon Jones vs Lyoto Machida
  "6f99a080-ea73-40fe-bee8-f5afe70121d0", // 2011-11-12 · UFC on FOX: Velasquez vs Dos Santos · Cain Velasquez vs Junior Dos Santos
  "9dbfc388-40d3-464e-994b-3dacc735dded", // 2011-10-08 · UFC 136: Edgar vs Maynard 3 · Frankie Edgar vs Gray Maynard
  "6bdf409b-e086-41b5-9ff6-abe6af597032", // 2011-10-08 · UFC 136: Edgar vs Maynard 3 · Jose Aldo vs Kenny Florian
  "4998e3c1-620f-4fc7-9261-cfd9c9db13ad", // 2011-10-01 · UFC Live: Cruz vs Johnson · Dominick Cruz vs Demetrious Johnson
  "3f0ae99f-b73a-4d4c-9d9e-c353b0e95960", // 2011-09-24 · UFC 135: Jones vs Rampage · Jon Jones vs Quinton Jackson
  "429be2bd-44a4-4c38-bad1-30d604406de7", // 2011-08-27 · UFC 134: Silva vs Okami · Anderson Silva vs Yushin Okami
  "ea17e614-fda7-4cb6-8bc8-77c451df9106", // 2011-07-02 · UFC 132: Cruz vs Faber · Dominick Cruz vs Urijah Faber
  "0d3431c9-20a5-4c21-a7ea-b6a85e85345a", // 2011-04-30 · UFC 129: St-Pierre vs Shields · Georges St-Pierre vs Jake Shields
  "f132337f-a83e-43de-b19a-25e96deb56a7", // 2011-04-30 · UFC 129: St-Pierre vs Shields · Jose Aldo vs Mark Hominick
  "25b8b090-82df-46ca-9f11-2dce11297f60", // 2011-03-19 · UFC 128: Shogun vs Jones · Mauricio Rua vs Jon Jones
  "41ae0b2c-9e4e-4f73-92ff-0893bd817c04", // 2011-02-05 · UFC 126: Silva vs Belfort · Anderson Silva vs Vitor Belfort
  "da775640-771a-472a-abb6-36893c009dab", // 2011-01-01 · UFC 125: Resolution · Frankie Edgar vs Gray Maynard
  "dc662a2a-0c14-46e9-a917-34558fd3fa17", // 2010-12-11 · UFC 124: St-Pierre vs Koscheck 2 · Georges St-Pierre vs Josh Koscheck
  "02e10d7f-07e9-4c04-bba9-5ea1f434cbe8", // 2010-10-23 · UFC 121: Lesnar vs Velasquez · Brock Lesnar vs Cain Velasquez
  "6434f443-73c4-476a-a8bc-0a91921c1820", // 2010-08-28 · UFC 118: Edgar vs Penn 2 · Frankie Edgar vs BJ Penn
  "65318723-f5b4-4dfb-a825-3441367b1f16", // 2010-08-07 · UFC 117: Silva vs Sonnen · Anderson Silva vs Chael Sonnen
  "c98e723b-6bac-4963-b4f9-eb1d45c97671", // 2010-07-03 · UFC 116: Lesnar vs Carwin · Brock Lesnar vs Shane Carwin
  "759a568f-dd66-46bd-8a3e-e026975f43c4", // 2010-05-08 · UFC 113: Machida vs Shogun 2 · Lyoto Machida vs Mauricio Rua
  "522786b9-16e0-47a1-9196-012efdf60361", // 2010-04-10 · UFC 112: Invincible · Anderson Silva vs Demian Maia
  "1ab24d6c-8083-49cf-bb32-0df276f5cf52", // 2010-04-10 · UFC 112: Invincible · BJ Penn vs Frankie Edgar
  "e3eb97d2-b0af-44f4-90e4-e74f49bcd478", // 2010-03-27 · UFC 111: St-Pierre vs Hardy · Shane Carwin vs Frank Mir
  "6b3d55b8-e5e7-4efe-9e33-bc3254198c8e", // 2010-03-27 · UFC 111: St-Pierre vs Hardy · Georges St-Pierre vs Dan Hardy
  "ae0fe036-f2ec-43fe-abc0-7135f1700162", // 2009-12-12 · UFC 107: Penn vs Sanchez · BJ Penn vs Diego Sanchez
  "3c7b541e-880f-428e-9804-3a17f7f6853b", // 2009-10-24 · UFC 104: Machida vs Shogun · Lyoto Machida vs Mauricio Rua
  "d6a7f9f5-8285-4cf4-9167-bfeee6f937bc", // 2009-08-08 · UFC 101: Declaration · BJ Penn vs Kenny Florian
  "eae34a9f-fc11-49ff-98b4-69fa00107095", // 2009-07-11 · UFC 100 · Brock Lesnar vs Frank Mir
  "0bfa2fde-1ce6-4f91-9330-957382847efc", // 2009-07-11 · UFC 100 · Georges St-Pierre vs Thiago Alves
  "90c53cff-e542-49d9-9292-36b3e929fc49", // 2009-05-23 · UFC 98: Evans vs Machida · Rashad Evans vs Lyoto Machida
  "9fb0483f-7ff0-4d16-97bf-b5d119b3e862", // 2009-04-18 · UFC 97: Redemption · Anderson Silva vs Thales Leites
  "89691df1-4949-47bc-aecf-7b624fea21c4", // 2009-01-31 · UFC 94: St-Pierre vs Penn 2 · Georges St-Pierre vs BJ Penn
  "83070d21-bb9c-4f11-9362-2f5f3e8e7f0b", // 2008-12-27 · UFC 92: The Ultimate 2008 · Antonio Rodrigo Nogueira vs Frank Mir
  "b916e771-7591-4d33-a59e-0d6157e5b227", // 2008-12-27 · UFC 92: The Ultimate 2008 · Forrest Griffin vs Rashad Evans
  "672283fc-bbf0-473d-80b1-c17ec17f6ce1", // 2008-11-15 · UFC 91: Couture vs Lesnar · Randy Couture vs Brock Lesnar
  "618ff237-5904-466e-a136-3fd1b6545754", // 2008-10-25 · UFC 90: Silva vs Cote · Anderson Silva vs Patrick Cote
  "eea8fc8e-6e68-4b2b-9eb5-e1c38dfa747e", // 2008-08-09 · UFC 87: Seek And Destroy · Georges St-Pierre vs Jon Fitch
  "d18a6a5a-2b8c-4c5a-b191-c964f075e9b4", // 2008-07-05 · UFC 86: Jackson vs Griffin · Quinton Jackson vs Forrest Griffin
  "46cb4d23-bafa-4df1-bf31-4fe41c32f721", // 2008-05-24 · UFC 84: Ill Will · BJ Penn vs Sean Sherk
  "554c6edf-e852-4864-9eab-0a9ccfd2e8c1", // 2008-04-19 · UFC 83: Serra vs St-Pierre 2 · Matt Serra vs Georges St-Pierre
  "869a86be-690c-4a79-8d8f-6b82ca0a4a88", // 2008-03-01 · UFC 82: Pride of a Champion · Anderson Silva vs Dan Henderson
  "89a370f9-6493-45d1-a46f-cd0be6dd6263", // 2008-02-02 · UFC 81: Breaking Point · Antonio Rodrigo Nogueira vs Tim Sylvia
  "94b2d254-5bcf-461e-9797-c84a81bad3f8", // 2008-01-19 · UFC 80: Rapid Fire · BJ Penn vs Joe Stevenson
  "0bb10884-c19f-4482-ab58-8974b4bc8206", // 2007-12-29 · UFC 79: Nemesis · Georges St-Pierre vs Matt Hughes
  "52ef1f41-e7d1-45c3-857e-378ff4bac32a", // 2007-10-20 · UFC 77: Hostile Territory · Anderson Silva vs Rich Franklin
  "91e725c3-9ebf-4f1a-8f86-db1ff17226cb", // 2007-09-08 · UFC 75: Champion vs Champion · Quinton Jackson vs Dan Henderson
  "10ddb80c-971d-4197-9812-c31ca6242e9f", // 2007-08-25 · UFC 74: Respect · Randy Couture vs Gabriel Gonzaga
  "c6024f4a-ed58-4478-bf43-a2ac38ab99f8", // 2007-07-07 · UFC 73: Stacked · Anderson Silva vs Nate Marquardt
  "5320c7be-0074-4710-9771-2d5566d3024b", // 2007-07-07 · UFC 73: Stacked · Sean Sherk vs Hermes Franca
  "f8ccb7f8-e136-4c1d-a60e-8ef53b2fd94f", // 2007-05-26 · UFC 71: Liddell vs Jackson · Chuck Liddell vs Quinton Jackson
  "46aa8158-2e40-4186-90fe-8de89db1443f", // 2007-04-07 · UFC 69: Shootout · Georges St-Pierre vs Matt Serra
  "bf648722-ee2a-4a6f-9dac-7407b7917094", // 2007-03-03 · UFC 68: The Uprising · Tim Sylvia vs Randy Couture
  "24838019-ac72-4de9-b0f2-922cf1debabe", // 2007-02-03 · UFC 67: All or Nothing · Anderson Silva vs Travis Lutter
  "19875a07-657b-4a69-bf37-e2122953aa31", // 2006-12-30 · UFC 66: Liddell vs Ortiz 2 · Chuck Liddell vs Tito Ortiz
  "c3e512bf-5a7c-4622-92e0-fce04eda4697", // 2006-11-18 · UFC 65: Bad Intentions · Tim Sylvia vs Jeff Monson
  "38a4b81b-2b2a-429d-8712-4d0cceacf1c4", // 2006-11-18 · UFC 65: Bad Intentions · Matt Hughes vs Georges St-Pierre
  "6029ad58-c7e3-4949-9821-048e11df1b60", // 2006-10-14 · UFC 64: Unstoppable · Rich Franklin vs Anderson Silva
  "ed2d2b12-ade1-4d85-a8e4-25989bda768d", // 2006-10-14 · UFC 64: Unstoppable · Sean Sherk vs Kenny Florian
  "d7538763-5b96-406f-bc93-b13d5eff6f3c", // 2006-09-23 · UFC 63: Hughes vs Penn · Matt Hughes vs BJ Penn
  "48c636a6-b4df-46b5-b722-77c3ec5195ef", // 2006-08-26 · UFC 62: Liddell vs Sobral · Chuck Liddell vs Renato Sobral
  "dec5e996-ffbf-44e9-b2ee-6989240710c3", // 2006-07-08 · UFC 61: Bitter Rivals · Tim Sylvia vs Andrei Arlovski
  "170ead1b-b6b6-4d95-b109-9b9d1ea9e251", // 2006-04-15 · UFC 59: Reality Check · Andrei Arlovski vs Tim Sylvia
  "cfae8f58-2bcf-4624-9029-3ceb822ed7af", // 2006-03-04 · UFC 58: USA vs Canada · Rich Franklin vs David Loiseau
  "a0217b7c-cede-45c2-a20e-6873f7c63d62", // 2006-02-04 · UFC 57: Liddell vs Couture 3 · Chuck Liddell vs Randy Couture
  "37e08979-2fc5-4175-ad1c-b3f70516716f", // 2005-11-19 · UFC 56: Full Force · Rich Franklin vs Nate Quarry
  "8a1c4098-e77e-434e-a9e6-e2b1f5e71e71", // 2005-11-19 · UFC 56: Full Force · Matt Hughes vs Joe Riggs
  "9b888c50-c447-4538-976c-ee7735591e9e", // 2005-10-07 · UFC 55: Fury · Andrei Arlovski vs Paul Buentello
  "b9c18e0f-749c-4409-b069-6f9c7213b78e", // 2005-08-20 · UFC 54: Boiling Point · Chuck Liddell vs Jeremy Horn
  "20f185f7-8e40-42e1-8d0c-b1cc2598d145", // 2005-06-04 · UFC 53: Heavy Hitters · Andrei Arlovski vs Justin Eilers
  "bf31cd44-4ca6-4e03-9c85-69e40bc715a5", // 2005-06-04 · UFC 53: Heavy Hitters · Evan Tanner vs Rich Franklin
  "0ef71662-98ab-41b2-b2e7-17a880d07255", // 2005-04-16 · UFC 52: Couture vs Liddell 2 · Randy Couture vs Chuck Liddell
  "066cc54f-db0d-475d-bc7c-6b3be950f1e7", // 2005-04-16 · UFC 52: Couture vs Liddell 2 · Matt Hughes vs Frank Trigg
  "c2b95442-6cd9-4d21-8c15-be0d1a6f8fae", // 2005-02-05 · UFC 51: Super Saturday · Andrei Arlovski vs Tim Sylvia
  "edf31b04-88c4-45fd-80eb-f9c462c9d0c8", // 2005-02-05 · UFC 51: Super Saturday · Evan Tanner vs David Terrell
  "53ba2186-2cb7-4fdd-a323-6558117480d4", // 2004-10-22 · UFC 50: The War Of '04 · Matt Hughes vs Georges St-Pierre
  "60ae4120-f607-4c3d-888c-9af3425eed7b", // 2004-08-21 · UFC 49: Unfinished Business · Vitor Belfort vs Randy Couture
  "619db2dc-ee4c-4128-85d5-6fd5a1b6d33f", // 2004-06-19 · UFC 48: Payback · Frank Mir vs Tim Sylvia
  "4a65bc86-42ac-4633-9ca4-cdb24c1baaee", // 2004-01-31 · UFC 46: Supernatural · Randy Couture vs Vitor Belfort
  "5a3a76b1-680c-4ee9-9340-f2a78ab9efeb", // 2004-01-31 · UFC 46: Supernatural · Matt Hughes vs BJ Penn
  "6adbc86d-14a8-4a3b-8922-23e0aaa6dc6e", // 2003-11-21 · UFC 45: Revolution · Matt Hughes vs Frank Trigg
  "ce28aadb-8b7d-4b01-b98a-69e95dfc6306", // 2003-09-26 · UFC 44: Undisputed · Tito Ortiz vs Randy Couture
  "23dfd92d-c713-406a-a1f2-66310b6b470c", // 2003-06-06 · UFC 43: Meltdown · Randy Couture vs Chuck Liddell
  "57b67255-8806-48af-8307-195f3a7a6a8f", // 2003-04-25 · UFC 42: Sudden Impact · Matt Hughes vs Sean Sherk
  "ad5bd1b5-737b-4786-9a2e-e81a8736197a", // 2003-02-28 · UFC 41: Onslaught · Ricco Rodriguez vs Tim Sylvia
  "67ff576c-8f78-4049-b0ef-240fbb551cd6", // 2002-11-22 · UFC 40: Vendetta · Tito Ortiz vs Ken Shamrock
  "94d21b5d-242d-4fe9-9e7b-9b1df6e5f22c", // 2002-11-22 · UFC 40: Vendetta · Matt Hughes vs Gil Castillo
  "04548ac2-a9ab-40b9-a968-9d588084feca", // 2002-09-27 · UFC 39: The Warriors Return · Ricco Rodriguez vs Randy Couture
  "ceb1ec98-d1a4-47b9-ac00-68dceb83f47a", // 2002-07-13 · UFC 38: Brawl at the Hall · Matt Hughes vs Carlos Newton
  "295bc6ba-0583-46aa-8d90-f8e51749eacc", // 2002-05-10 · UFC 37: High Impact · Murilo Bustamante vs Matt Lindland
  "ac96988f-2b85-4736-96d8-a415bd57eb64", // 2002-03-22 · UFC 36: Worlds Collide · Randy Couture vs Josh Barnett
  "4365fc69-442f-4b97-bb77-c7a5ec09ceee", // 2002-03-22 · UFC 36: Worlds Collide · Matt Hughes vs Hayato Sakurai
  "43e67d26-d57d-4079-a666-3195bda7c71a", // 2002-01-11 · UFC 35: Throwdown · Dave Menne vs Murilo Bustamante
  "65d31cd1-5020-494e-b237-8bae31a81e36", // 2002-01-11 · UFC 35: Throwdown · Jens Pulver vs BJ Penn
  "c3113b05-b291-4057-8bd6-932711cf8818", // 2001-11-02 · UFC 34: High Voltage · Randy Couture vs Pedro Rizzo
  "4027546e-703c-4fe3-9820-ef06b97b5cc8", // 2001-11-02 · UFC 34: High Voltage · Carlos Newton vs Matt Hughes
  "2aebad67-2955-4c24-9a4a-c3924ec826cd", // 2001-09-28 · UFC 33: Victory in Vegas · Tito Ortiz vs Vladimir Matyushenko
  "5a3f3bf5-6f9c-4d1b-82cd-aedb00567544", // 2001-09-28 · UFC 33: Victory in Vegas · Dave Menne vs Gil Castillo
  "e80e1590-05b4-442b-995f-7025bd9db9e8", // 2001-09-28 · UFC 33: Victory in Vegas · Jens Pulver vs Dennis Hallman
  "3cc0cf08-b631-4929-9a34-ffb5b5d8fdc4", // 2001-06-29 · UFC 32: Showdown in the Meadowlands · Tito Ortiz vs Elvis Sinosic
  "42a0bc2b-e615-4e3f-8aee-b1eed4f9a71c", // 2001-05-04 · UFC 31: Locked and Loaded · Randy Couture vs Pedro Rizzo
  "da77bdf8-b3d2-4ded-ba39-b2a8250d1385", // 2001-05-04 · UFC 31: Locked and Loaded · Pat Miletich vs Carlos Newton
  "d3b8c650-c308-4023-a56b-c35d350af0ab", // 2001-02-23 · UFC 30: Battle on the Boardwalk · Tito Ortiz vs Evan Tanner
  "1902cff3-f576-42a7-b5b8-0393926e42b2", // 2001-02-23 · UFC 30: Battle on the Boardwalk · Jens Pulver vs Caol Uno
  "11d07f24-8f46-44eb-8dab-3e39c70a4683", // 2000-12-16 · UFC 29: Defense of the Belts · Tito Ortiz vs Yuki Kondo
  "f370af79-2179-4b48-ba2a-98cd33d85f8b", // 2000-12-16 · UFC 29: Defense of the Belts · Pat Miletich vs Kenichi Yamamoto
  "df8abdca-64b4-4028-9893-48e581dae481", // 2000-11-17 · UFC 28: High Stakes · Kevin Randleman vs Randy Couture
  "ec905a23-487f-414f-8b0f-ba230fe5208e", // 2000-06-09 · UFC 26: Ultimate Field Of Dreams · Kevin Randleman vs Pedro Rizzo
  "b11bd05a-167d-41ce-898b-0fd314d35796", // 2000-06-09 · UFC 26: Ultimate Field Of Dreams · Pat Miletich vs John Alessio
  "080aa7cd-9693-40df-82bd-c2af9e6671b9", // 2000-04-14 · UFC 25: Ultimate Japan 3 · Tito Ortiz vs Wanderlei Silva
  "764afa7b-fb47-4a72-bee5-002421d5482c", // 1999-11-19 · UFC 23: Ultimate Japan 2 · Kevin Randleman vs Pete Williams
  "85cfd672-4194-467c-b898-ea1714f21e56", // 1999-09-24 · UFC 22: Only One Can be Champion · Frank Shamrock vs Tito Ortiz
  "2e76aed5-fbf6-4595-bb1f-118580071dff", // 1999-07-16 · UFC 21: Return of the Champions · Pat Miletich vs Andre Pederneiras
  "35a938fb-bea5-4e83-b6f1-347914f01e07", // 1999-05-07 · UFC 20: Battle for the Gold · Bas Rutten vs Kevin Randleman
  "001027e8-ef5f-4de9-8caa-89e695490a91", // 1999-01-08 · UFC 18: The Road to the Heavyweight Title · Pat Miletich vs Jorge Patino
  "60364a5f-2841-4358-81a6-bc375a23fd71", // 1998-10-16 · UFC - Ultimate Brazil · Frank Shamrock vs John Lober
  "dcd5c700-482a-4038-bba1-54f9d383e096", // 1998-10-16 · UFC - Ultimate Brazil · Pat Miletich vs Mikey Burnett
  "559b31af-33d4-4be2-ba24-3d0e78f5d88c", // 1998-05-15 · UFC 17: Redemption · Frank Shamrock vs Jeremy Horn
  "15de3022-f0f9-4e18-8277-72b672095f1e", // 1998-03-13 · UFC 16: Battle in the Bayou · Frank Shamrock vs Igor Zinoviev
  "2f073b05-824e-41c4-b79c-626d390c2080", // 1997-12-21 · UFC - Ultimate Japan · Maurice Smith vs Randy Couture
  "9c7fe7c7-f89e-4654-b3a7-3cbcab844f67", // 1997-12-21 · UFC - Ultimate Japan · Frank Shamrock vs Kevin Jackson
  "0bd61b52-37d0-4a52-bcca-51bf81d33398", // 1997-10-17 · UFC 15: Collision Course · Maurice Smith vs David Abbott
  "f369699f-4d91-42bb-a501-2c20e4321c2d", // 1997-07-27 · UFC 14: Showdown · Mark Coleman vs Maurice Smith
  "f898cbf3-6d21-405e-8454-94bf626b6e03", // 1997-02-07 · UFC 12: Judgement Day · Dan Severn vs Mark Coleman
  "14690e3a-ce09-43f8-8036-98279ef43a4d", // 1996-05-17 · UFC 9: Motor City Madness · Ken Shamrock vs Dan Severn
  "6a841a20-09ca-4f46-b56d-59837a0be54d", // 1996-02-16 · UFC 8: David vs Goliath · Ken Shamrock vs Kimo Leopoldo
  "dfb6f248-0d1c-4bc2-8446-2a6b4ae457d8", // 1995-09-08 · UFC 7: The Brawl in Buffalo · Ken Shamrock vs Oleg Taktarov
  "795acc7c-5e41-4527-bfce-2d074b817c87", // 1995-07-14 · UFC 6: Clash of the Titans · Ken Shamrock vs Dan Severn
];

const TITLE_BOUT_SET: ReadonlySet<string> = new Set(CURATED_TITLE_BOUT_IDS);

/** Returns true if the bout is a known title fight per the curated list. */
export function isCuratedTitleFight(boutId: string | null | undefined): boolean {
  if (!boutId) return false;
  return TITLE_BOUT_SET.has(boutId);
}
