import { sql } from "drizzle-orm";
import {
  type AnyPgColumn,
  boolean,
  check,
  index,
  integer,
  jsonb,
  pgTable,
  real,
  text,
  timestamp,
  unique,
  uuid,
  vector,
} from "drizzle-orm/pg-core";

import { newsClassificationEnum, newsStatusEnum } from "./enums";
import { bout } from "./events";
import { userProfile } from "./users";

/** Structured social/video references extracted from the source article at
 *  ingest. Rendered as inline platform-icon links (role=inline), big social
 *  cards (role=featured), or compact stacked cards (role=reaction). */
export type NewsExternalRef = {
  kind: "instagram" | "twitter" | "x" | "youtube" | "tiktok" | "link";
  url: string;
  /** Text in the article that pointed at this URL — used by the autolinker
   *  to find where to render an inline link or a featured embed. */
  anchor: string;
  role: "featured" | "inline" | "reaction";
  author?: string | null;
  handle?: string | null;
  /** Post body, if Haiku could extract it from the source HTML. */
  quote?: string | null;
  posted_at?: string | null;
  thumbnail_url?: string | null;
  duration?: string | null;
};

export const newsSource = pgTable("news_source", {
  id: uuid("id").primaryKey().defaultRandom(),
  slug: text("slug").notNull().unique(),

  name: text("name").notNull(),
  url: text("url").notNull(),
  feedUrl: text("feed_url"),
  type: text("type").notNull(),

  isTrusted: boolean("is_trusted").default(false).notNull(),
  baseConfidence: real("base_confidence").default(0.5).notNull(),
  isActive: boolean("is_active").default(true).notNull(),

  lastFetchedAt: timestamp("last_fetched_at", { withTimezone: true }),

  createdAt: timestamp("created_at", { withTimezone: true })
    .defaultNow()
    .notNull(),
});

export const newsItem = pgTable(
  "news_item",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    sourceId: uuid("source_id")
      .notNull()
      .references(() => newsSource.id),

    externalId: text("external_id"),
    url: text("url").notNull().unique(),

    title: text("title").notNull(),
    body: text("body"),
    bodyRephrased: text("body_rephrased"),
    // Russian renderings for the RU locale, generated by the news translator
    // (scripts/15_translate_news.py). Null until translated; the UI falls back
    // to the English title / body_rephrased.
    titleRu: text("title_ru"),
    bodyRephrasedRu: text("body_rephrased_ru"),
    author: text("author"),
    // Lead image for the feed/cards — og:image from the article (or a
    // media:thumbnail / enclosure straight off the RSS entry). Nullable; the
    // UI omits the thumbnail when absent.
    imageUrl: text("image_url"),

    publishedAt: timestamp("published_at", { withTimezone: true }).notNull(),
    fetchedAt: timestamp("fetched_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
    processedAt: timestamp("processed_at", { withTimezone: true }),

    classification: newsClassificationEnum("classification"),
    confidence: real("confidence"),

    // ON DELETE SET NULL: news auto-creates provisional bouts that the UFCStats
    // scrape later reconciles by DELETEing the provisional row. Without this,
    // the default RESTRICT blocks any bout delete that a news item still points
    // at (the scraper only works because it manually repoints first); a news
    // item simply keeps its body when its provisional bout is reconciled away.
    relatedBoutId: uuid("related_bout_id").references(() => bout.id, {
      onDelete: "set null",
    }),
    relatedFighterIds: uuid("related_fighter_ids")
      .array()
      .default(sql`'{}'::uuid[]`),

    status: newsStatusEnum("status").default("pending").notNull(),

    embedding: vector("embedding", { dimensions: 384 }),

    externalRefs: jsonb("external_refs")
      .$type<NewsExternalRef[]>()
      .default(sql`'[]'::jsonb`)
      .notNull(),
  },
  (table) => [
    index("news_item_published_idx").on(table.publishedAt),
    index("news_item_status_idx").on(table.status),
    index("news_item_classification_idx").on(table.classification),
    index("news_item_related_bout_idx").on(table.relatedBoutId),
    // GIN index on the uuid[] of tagged fighters: the per-fighter feed lookup
    // (listNewsForFighter) filters with `related_fighter_ids @> ARRAY[id]`,
    // which uses this index instead of a full scan that grows with the table.
    index("news_item_related_fighters_gin").using(
      "gin",
      table.relatedFighterIds,
    ),
  ],
);

/** User comments on news articles. App-layer auth: every insert goes through
 *  a server action that validates getCurrentUser(). RLS policies are deferred
 *  to Wave 3 per project plan. Replies are limited to depth 1 by the API
 *  layer — no nested threading. Deletion is soft via `deletedAt`. */
export const newsComment = pgTable(
  "news_comment",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    newsItemId: uuid("news_item_id")
      .notNull()
      .references(() => newsItem.id, { onDelete: "cascade" }),
    userProfileId: uuid("user_profile_id")
      .notNull()
      .references(() => userProfile.id, { onDelete: "cascade" }),
    /** NULL for top-level comments; a comment id for replies. Replies-of-replies
     *  are flattened to the same parent at the API layer. Self-FK with
     *  ON DELETE CASCADE: hard-deleting a parent comment removes its replies. */
    parentId: uuid("parent_id").references((): AnyPgColumn => newsComment.id, {
      onDelete: "cascade",
    }),
    body: text("body").notNull(),
    upvotes: integer("upvotes").default(0).notNull(),
    downvotes: integer("downvotes").default(0).notNull(),
    createdAt: timestamp("created_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
    deletedAt: timestamp("deleted_at", { withTimezone: true }),
  },
  (table) => [
    index("news_comment_item_created_idx").on(
      table.newsItemId,
      table.createdAt,
    ),
    index("news_comment_parent_idx").on(table.parentId),
    index("news_comment_user_idx").on(table.userProfileId),
    check(
      "news_comment_body_length",
      sql`char_length(body) BETWEEN 1 AND 2000`,
    ),
  ],
);

/** Reader-submitted abuse/spam reports on a comment. One row per reporter per
 *  comment (unique). Staff act on these via the admin-email allowlist; for now
 *  they surface as a count and let staff soft-delete the comment. */
export const newsCommentFlag = pgTable(
  "news_comment_flag",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    commentId: uuid("comment_id")
      .notNull()
      .references(() => newsComment.id, { onDelete: "cascade" }),
    userProfileId: uuid("user_profile_id")
      .notNull()
      .references(() => userProfile.id, { onDelete: "cascade" }),
    /** Optional short reason chosen by the reporter. */
    reason: text("reason"),
    createdAt: timestamp("created_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
    /** Set when staff has actioned/dismissed the report. */
    resolvedAt: timestamp("resolved_at", { withTimezone: true }),
  },
  (table) => [
    unique("news_comment_flag_unique").on(table.commentId, table.userProfileId),
    index("news_comment_flag_comment_idx").on(table.commentId),
  ],
);

/** One up/down vote per user per comment. `dir` is +1 (up) or -1 (down). The
 *  denormalized upvotes/downvotes counts on news_comment are recomputed from
 *  this table on each vote. */
export const newsCommentVote = pgTable(
  "news_comment_vote",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    commentId: uuid("comment_id")
      .notNull()
      .references(() => newsComment.id, { onDelete: "cascade" }),
    userProfileId: uuid("user_profile_id")
      .notNull()
      .references(() => userProfile.id, { onDelete: "cascade" }),
    dir: integer("dir").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
  },
  (table) => [
    unique("news_comment_vote_unique").on(table.commentId, table.userProfileId),
    index("news_comment_vote_comment_idx").on(table.commentId),
  ],
);
