-- Wave 60: era_dominance_current rescaled to 0-100 parity, sourced
-- from curated title fights.
--
-- The component was the lone 0-10-scale input in the current formula
-- (title fight in 24mo → +5, ≥2 title fights in 36mo → +5, cap 10), so
-- at weight 0.06 its maximum contribution was 0.6 raw points. Same
-- signal, ×10 scale (50/50, cap 100): the unchanged 0.06 weight now
-- contributes up to 6.0 raw points.
--
-- The title-fight source moves from the scraped bout.is_title_fight
-- (over-flagged: UFCStats puts bonus icons in the belt's cell, so whole
-- main-card slates get marked — 460 "title bouts" in 36mo vs 57 real)
-- to the new title_fight_bout table, seeded here from the curated
-- src/lib/title-fights.ts and kept in sync by
-- scripts/derive_title_fights.ts. The boost therefore lands only on
-- actual champions and recent title challengers.
--
-- Applied to BOTH views (global + divisional). The history replay
-- (scripts/compute_score_history.ts) gets the matching changes in the
-- same commit.
--
-- GENERATED by scripts/generate_wave60.ts from 0076 — do not hand-edit.
--
-- Re-materialize after applying:
--   pnpm tsx scripts/materialize_vertex_score.ts
--   pnpm tsx scripts/materialize_divisional_score.ts

-- Curated title-fight bout IDs (mirrors src/lib/title-fights.ts).
-- Synced by scripts/derive_title_fights.ts on every re-derive; the
-- INSERT ... JOIN below only seeds rows whose bout still exists.
CREATE TABLE IF NOT EXISTS title_fight_bout (
  bout_id uuid PRIMARY KEY REFERENCES bout(id) ON DELETE CASCADE
);

DELETE FROM title_fight_bout;

INSERT INTO title_fight_bout (bout_id)
SELECT b.id
FROM bout b
JOIN (VALUES
  ('e7569169-e92d-4f34-ab06-6cedb9bb4789'),
  ('ed2fa2cd-0896-40e3-9fd3-ef9b33e1377a'),
  ('93c107a5-7b18-401c-8271-794b89e41763'),
  ('5aeba8c9-c220-44b3-aed8-3fdd5652b3e3'),
  ('d888680c-fa68-47fb-8b9f-35f3b41a27d2'),
  ('ecdb40c4-4801-49a8-b39a-9101b376f9ed'),
  ('d31d490d-2ffb-4ea9-8aaa-f96cce77955d'),
  ('eab763ca-5d01-4e3e-96db-3af23d4e7330'),
  ('5c96e392-0e82-4186-9616-db6e0bcb721d'),
  ('44eba65e-3aa5-4f83-a716-8b25193e0627'),
  ('0f453494-d9db-4c99-8bc0-c00d948e411a'),
  ('a4bc2812-2ff7-441a-aff0-96bd16a954ae'),
  ('03ba29d4-9423-4ede-9abf-16ddeaa4ee83'),
  ('81ee0fdf-bee0-4911-8c91-9718ef5fa482'),
  ('7dbd3c09-b6cd-447c-bd93-fc4376139eb7'),
  ('af3ddee2-6346-4b57-b65e-76ce38faf376'),
  ('887df5eb-11c6-4a5c-9bd0-21193040b9a5'),
  ('45ef0f4c-2513-4714-acbf-e2373e57b0e3'),
  ('f0039537-02e3-4092-8918-f285612b57c7'),
  ('bc22987a-fda3-4c29-aab5-d09542560b1a'),
  ('7bd98524-718e-4835-85cc-a5590ec72c79'),
  ('46061d6f-04eb-43a4-b34d-0a3bbed957f4'),
  ('ecca6af1-f088-4460-8a4c-5e744dbd5b14'),
  ('2bf4c511-931f-4474-a41b-762a810b4bd4'),
  ('4e8868a8-8ac4-456e-8e41-6e086812daa3'),
  ('fda6561d-2272-4087-b4f5-96f13dc857d9'),
  ('d023b42f-e0b0-445f-a855-0cb37a0c18cf'),
  ('901d0fcb-b798-482d-a11f-c20ddfc6db1d'),
  ('ffc36d5e-4881-4bdf-a8ac-8d7d477aa8a3'),
  ('efd1b690-58ed-4222-af8b-4733f67805fb'),
  ('fc7a7461-cbcf-499b-a077-2879bf1dd304'),
  ('dea47513-e078-4a0b-a5bd-fde087325883'),
  ('2fd5e96c-fd44-4046-b071-11fe000de920'),
  ('cef7a11d-37bd-46a4-9f34-1675fd681875'),
  ('a52a70d9-ff4b-488a-aeb0-2336abb1d552'),
  ('1c63c3df-7af4-49d4-8ea6-cb44a8d351a1'),
  ('00f83584-457a-4aaa-b3e6-a96b81ae147c'),
  ('f1afe409-c54a-4d53-a6c3-bb6536fbdf08'),
  ('4b32b412-d4b0-4121-949d-5b47cef9669d'),
  ('aa4e5169-392e-4152-ab4d-eaaeda6af2ab'),
  ('d07fe53b-780b-431c-94d6-d17efbf5ff10'),
  ('ffa833fc-42cc-4679-ab12-1166de48ec3d'),
  ('cda9db87-acdb-4024-bf0b-289bfad6cb9d'),
  ('9a8affe6-e150-4c2f-a1c7-661055cb8bea'),
  ('d00a9693-9d21-4116-970d-e50b4b8ea163'),
  ('433b018f-3e70-4f9d-98c3-44952709bd41'),
  ('25fe2137-6e18-40f5-9399-63831a441049'),
  ('69d78d34-c429-40bc-a197-baf8fac7a613'),
  ('e90ff4cb-495c-4b12-afd6-3a6a2cfc083e'),
  ('8c09c4fd-6408-4cb7-a549-c83de419cb08'),
  ('2eaba757-6d32-49c1-a8f4-2263c65fbea0'),
  ('d5426913-85e9-4577-a444-445196ad347f'),
  ('bf57f5bd-3823-415b-ac5a-d0556421ad80'),
  ('0b909120-0c18-4ba9-93f0-3c1257524331'),
  ('7d69c83c-eab7-4fc3-b94b-bc06d7c7c741'),
  ('6ddeb49f-1b46-4534-90c6-535ce62d29d0'),
  ('21447804-cd8e-4deb-8f4d-7a7589a08da3'),
  ('bf2e9966-63ab-49bf-b287-d55d57bdefde'),
  ('647e2d30-fd67-4a16-ae20-bf5869595027'),
  ('b0a4a716-c88a-46cb-bab0-586de7353517'),
  ('20cf9ba1-ab8b-48fa-9019-c9dd1e1d418b'),
  ('496b0f44-16d4-470a-adcf-5d3612bb69f4'),
  ('14e8e1b7-7737-4356-a231-e88bbed0595c'),
  ('f59ccb46-994f-448f-aba2-7648f06608ce'),
  ('c885ccd5-ef3b-4576-bc25-64d8d1bee595'),
  ('0089d23d-8b89-42d7-85b8-034534fe9453'),
  ('1c9a2c8c-33bb-4f5c-b653-38c216f0adc5'),
  ('08bb907b-75fd-4af7-8b95-473941e8483e'),
  ('b3ddefc0-898b-4527-b910-3c9fa0bbe3fb'),
  ('242c37b6-f1b8-4f5a-88a8-25e58abadf55'),
  ('fa399fec-ba48-4fb0-8665-a9de1f3ddb2d'),
  ('a55bcbb5-f4fa-4742-8f49-9365c998dc1b'),
  ('01bb914d-f42e-4a6f-9caf-7f21e4c915c1'),
  ('a9315097-35b4-42a6-91cc-76393e9db057'),
  ('13dfdf5a-d853-43ef-9f3f-18bd1608db9e'),
  ('0c5ee48b-ca9e-4d73-9e56-c8bc0d670986'),
  ('43d29794-9d1d-45cc-ba65-59f977796a73'),
  ('69d811ca-72f4-46b0-9540-ff4689e2a339'),
  ('111ccda1-42f7-45f1-b2ec-814fdff1904e'),
  ('7fc11f68-361d-4cbb-be43-dafcbf2a3e62'),
  ('0b01f17c-5e43-4cb0-8bf4-7771d7017485'),
  ('872396b7-cbd7-4491-915e-985a91aa3241'),
  ('4179feb6-1f88-4657-8bf9-829219cc06a6'),
  ('8b16e6dc-6ff6-4c1f-b362-b3f503c8dd72'),
  ('792bd1fd-1b10-431b-9277-a0c57176cc61'),
  ('872fbf04-703e-4f98-8572-f763380e4539'),
  ('065209d2-f982-42d5-ab98-e89e80a72d5b'),
  ('60d4b96e-3efd-4fdb-8089-ca5a42667b46'),
  ('97989a11-4ba7-41ab-9fca-b0798ae8988a'),
  ('434ff80a-21f9-434b-9de3-ed7dd388979b'),
  ('dd7afe4a-d6cd-4d7a-8ddc-cad9b1647489'),
  ('81224429-98b7-45d1-9a89-c6f72d9a9155'),
  ('a1cb52af-447a-4c51-8d53-acdae306c4c8'),
  ('abc01963-3198-4a14-a2c1-e880bcf39fc3'),
  ('1dc5a51a-65c1-450c-b7ed-8f4607dd47b4'),
  ('20abdf73-40b6-48be-9f9e-84aeb2a938f4'),
  ('98b29a87-e099-45b9-88e9-3e3470a0dac5'),
  ('9a3fbfbc-4adc-45ce-b115-8e0b69b8480b'),
  ('4fc40d68-002c-4de9-b9c3-a4e68b17ff69'),
  ('ff18ce2c-f87a-4b43-8075-87b1cd0c5fd9'),
  ('302d7626-1736-4777-b6bc-0f808720d808'),
  ('f0c4b211-e583-4206-81d9-84e650318e8c'),
  ('e63793e6-2993-4168-9a1d-95c4ea30c06a'),
  ('f5be6bf1-9799-4623-a2e0-f58654ea042d'),
  ('7030b5b8-4115-4b30-8415-027d42d2654a'),
  ('402e6b67-5e1c-4131-9ab4-2740e2267968'),
  ('6fedd96f-44ae-40b9-a47e-23900be203a9'),
  ('d4de2e15-6179-48f0-a627-d6bd71f5a772'),
  ('1e17ea53-63f0-4a44-b644-79183c926294'),
  ('efc6abee-2fe3-4393-adc2-5d3c30a873c1'),
  ('9e21173a-933b-4f87-81d5-61ec7457cc1b'),
  ('ca0c6474-464e-4f5e-b858-e0b6de8fe490'),
  ('80777d32-78d7-46cb-96e1-84cad63096a7'),
  ('01e069f4-1bdc-4c21-9d3e-8d21713e4e36'),
  ('6c338ca8-0c05-4e7d-bf92-b9291bd4c584'),
  ('27087493-f8ac-470a-8950-6c80c0d84bcd'),
  ('3c15b87f-a49f-45ff-852b-2b58611dbd20'),
  ('649a95e2-8246-46d0-8fa4-49c65da85911'),
  ('eca02987-52a5-4f91-aa94-e46c2d932a9d'),
  ('d50651d3-d1f4-4edb-b04f-b6703647c1ae'),
  ('9c8e15af-08ff-45cb-a7cb-9a599a156045'),
  ('8a702bc4-2cce-464f-9524-45bd9da84156'),
  ('4e081b72-0bff-4f1d-85fc-214ad7389246'),
  ('6a489333-5a29-4756-bb21-6a1bdf32f205'),
  ('cda4f7d5-bcf7-4857-bb23-c4fb9198030c'),
  ('4e0a3273-adf7-45f1-9f92-dc09187c29e7'),
  ('1d0e8f8a-9624-4af7-b8f1-71a70f42bbd6'),
  ('f958c971-28df-4b2b-acde-1ccfe0a6a7fe'),
  ('7d1c03d3-62ea-4e63-acef-6e50fa835904'),
  ('b9b4532d-c372-49dd-b5ff-854d162c7bca'),
  ('c286ba57-3439-4ac7-a019-5e19effc3721'),
  ('31f293c8-473d-4bcf-aaf8-bceaf8b2b7ca'),
  ('e518d397-ca6d-445c-b07e-6909e7459776'),
  ('34c78393-0c94-416b-bbca-065bec1f533b'),
  ('d8887941-b6d5-4186-bdad-bf722a83f350'),
  ('cbdd6f5c-f450-4d00-baac-9ff732996559'),
  ('9fd25745-4557-41aa-944c-c6bf73dea9f9'),
  ('cedcd2a5-d5d4-4707-bc4d-e31260a12ed6'),
  ('9c81f8db-a76d-4f04-8119-7a705f432254'),
  ('f6f139e3-be17-4ac6-bbac-c5ddd0527377'),
  ('ec38efcc-3c21-487e-9d78-23d6820771ad'),
  ('cca69b12-493a-46fa-938e-f9072838f0c5'),
  ('f792a1bb-9fa7-4ec8-9804-a1ccdbda6ea0'),
  ('eb34edb9-bbef-45bf-a713-92ba0705b014'),
  ('6e5b0e88-1974-4a84-8b29-2e8ac05759ed'),
  ('d97e76c9-4afe-4bb2-9f36-b01e67b02c10'),
  ('b9b19c9e-5736-430b-87be-855f49f6fe6e'),
  ('9de4f46f-81f4-4545-acc3-d0df0275858c'),
  ('26b88b3b-df1a-47ad-af07-29ef492ab6a7'),
  ('d1a9e22e-1e87-41d3-9191-eb0e12118d38'),
  ('56e4ca42-fbc4-4f09-ad7d-b08dfb447429'),
  ('e78ad6ef-693b-4412-8b31-5202e0641afb'),
  ('4521828c-2aa8-40c7-9c70-9775dbbf3840'),
  ('ab636be2-a353-4abf-9844-22a268629366'),
  ('d59116c8-75bd-4e5b-9d66-99e823d52448'),
  ('ae81e13d-b48f-4dcd-b0b1-6696dcaff3bd'),
  ('aa1c065f-bc03-40e0-8698-f184fa2ca27e'),
  ('d17f745a-69cb-487e-896f-c4a3e8054704'),
  ('a437d892-3ae9-40b4-b2c7-5d8a5ee20fbe'),
  ('561b2dbc-e513-4c49-bfe4-3c1cc7a817a5'),
  ('51cc3bba-fa1f-4128-bf2e-ebe39334c104'),
  ('ad540294-6889-4e2d-acb6-e4396d6179ab'),
  ('2524f6b1-011f-4199-81d0-e8026461341a'),
  ('6b0897fd-70f1-411c-a681-5c8c2ce223c8'),
  ('dd3f9227-3c71-45fa-bc9b-05546f0a3df9'),
  ('3aac7198-8298-468c-8783-1980cce8976f'),
  ('bae7660c-cbae-4a05-9a38-d4e1f2b06a4f'),
  ('c0aaa1af-9ecc-4dba-a83b-d20e37473ec7'),
  ('0a85714f-d76a-4f72-bfb8-ff15a0078745'),
  ('de9b702f-2d9c-4972-9e70-3df281ef8de7'),
  ('5efb55f9-c70f-485a-88e5-5d4838ec6630'),
  ('9d67c8b2-cb4a-41e8-8a3e-1abba2823cad'),
  ('595f4e9b-151d-49bd-b58d-8e727c5bd61c'),
  ('edb7466a-cd3d-48b8-b822-1fd708ec74aa'),
  ('b058b2db-9809-40d1-9d56-37f2ce297950'),
  ('90967d2d-5708-4026-bcd0-321421bbd064'),
  ('f0517cf4-dfa5-4758-88d3-b68c6cf0aa2c'),
  ('fb416162-4d98-4174-a23b-a46bbf68186d'),
  ('13c798e4-720f-4595-83f1-bf253c5aacd7'),
  ('39a4c56b-6d8e-456f-bd49-cb86ada52870'),
  ('e3704ede-f982-492d-99dc-a00c3f98ee31'),
  ('fe369cbb-5d85-4ba2-859f-ae03f562e682'),
  ('c22ef5cd-a647-45c7-94fc-635da620c2b0'),
  ('f3990995-bb6d-4dbe-9650-3d090d9c42dd'),
  ('3f53b33f-8ae3-4182-baa9-dd5932d81a03'),
  ('f55f2019-330c-4080-9180-c877ef8afa67'),
  ('9ed3e7d3-41bc-4fa1-b952-f7d2f658d69e'),
  ('075df8cb-ce80-438c-8f92-d1d8e08ba159'),
  ('1ef6ea0c-c766-4056-bc17-1fe31c071c0f'),
  ('a8551a8d-f0d0-4c47-ab8d-05a72ccfc41f'),
  ('a9ab8690-16a0-4552-825c-7567bb6d7e96'),
  ('d0ce3887-ffe0-4134-ab38-12a529779fde'),
  ('9b2f5397-b0dc-4a3b-8f9f-5ef3eb494aea'),
  ('3a2a660b-d81f-4ee6-91a3-aa255b2d676a'),
  ('0e0dde20-82f2-4bd2-9b6c-9632332e10bf'),
  ('f479a2e5-6eaa-468c-bd8c-ebc13a0df549'),
  ('ad7fd325-86d1-4536-a609-4a576c1fc54e'),
  ('abeee5b9-a0b0-4254-9d18-39fd7c1afec4'),
  ('fed84909-4f5a-4eb5-8ac6-3b71af1f1f32'),
  ('f8d2b184-050e-45e5-afc5-4a4b476437be'),
  ('2370b147-365f-4021-845e-06e2f7d1ab3b'),
  ('837e76b5-b4e8-4f35-a1a0-bcbc663f364d'),
  ('b09a24c6-85eb-427c-88cb-85b8a3ecb821'),
  ('9c9613d3-6171-4164-99f2-461b1d6d7c90'),
  ('777d6b35-eb53-4948-9ee3-891b8522ae66'),
  ('c7269b5e-5ebb-4ade-84b4-5e03a5c35aec'),
  ('a797035a-13c5-4fbf-9809-6837e0d18218'),
  ('14905c01-d9cd-4def-a358-18c374ac5e4b'),
  ('7c48be48-d417-4743-a12f-119f5b89d0c9'),
  ('56e0e50a-f990-4b21-9ccf-ff1ba1b7487e'),
  ('b88815af-6d92-442f-9698-cd84df955352'),
  ('aa6cde41-14d1-4584-ba33-e020b4994935'),
  ('904271d1-066a-4676-b52b-16433db50dd4'),
  ('b035f3ac-88f6-4841-b3a9-9a84d7ca3e88'),
  ('09b2fdc9-7f00-4a9b-ad71-a92d0a9c3296'),
  ('070fe7a1-47f6-47ca-8aad-a0f62c40ee72'),
  ('c690eb62-63d0-42f9-9e67-20b9b4702568'),
  ('b8193c2d-cacc-42e6-a0bb-ee1243035e46'),
  ('e9e18c86-e778-4725-9aa1-40a7999368b5'),
  ('11afcc5f-9aa0-4cf3-b7e5-e53ec884fd9b'),
  ('01f193ad-9df0-4e8e-83c4-0c294a1ff9f3'),
  ('92ddba48-288d-49f0-901c-7396ed0f9487'),
  ('d983a835-8c5e-40ff-8070-742a92738db0'),
  ('d80c400c-cac4-4a63-b1e2-9001a2104d6b'),
  ('0e6bb0b0-cc58-4ba2-9a8a-bfe05ded821b'),
  ('ca352025-b3c1-4ac4-8f55-02e63b609b41'),
  ('aeb852cb-c218-497a-a6b6-8eb860bf990d'),
  ('e6007514-fb08-411a-bb07-3388eb710e39'),
  ('61e44f34-4951-42ec-a637-f8ea71dfd83f'),
  ('a2abe490-a123-4b33-b931-7ec0a03ddf5a'),
  ('6b3356ae-fc7f-4f2f-b631-0fed34bc969e'),
  ('4ae62fbc-75f4-4e91-a4bd-3ac4d1c75057'),
  ('02483fcd-6473-4a46-9f31-54369ecdf402'),
  ('7a6668eb-106d-44b9-bb87-41ac8a2e547f'),
  ('dd5465c7-be1c-4f37-a4a1-b34e653f074e'),
  ('3afeb6ca-472a-43da-b12c-73680fd6a1f1'),
  ('cdda8df4-1d3e-4234-b9ce-2652da0d6da7'),
  ('b2c30485-364b-4d1d-bddf-008d23936641'),
  ('566b455c-6a30-4969-bbdf-47337d12d0d2'),
  ('9cab4230-b861-4a2d-93ac-f95c5c8bfde2'),
  ('145b251c-42ac-468f-b933-c6fe828bcb26'),
  ('19476fbb-d3b3-4ebe-92d8-80684e54b2dd'),
  ('0c167492-1af3-4fd1-84ef-9b99ce3ce725'),
  ('24a2b420-8348-4221-b74b-a22f12e18282'),
  ('7b54b0bb-bebf-403b-8fb0-302b42aa7de5'),
  ('e7c271c5-2040-4177-bfa6-7e3c4a8d0c68'),
  ('8de4b7e9-f1e4-4a22-a2b6-b4348ab37307'),
  ('1d83f335-eb95-4e4c-9930-c83f76c8edfb'),
  ('4e69684a-adeb-40cf-ad63-03afc5a703b1'),
  ('27cee30d-deaf-451c-b0a8-27aa2061619a'),
  ('ca21e349-805d-4024-a68d-dd9ad7900c9e'),
  ('a3b63f03-5b49-454a-a2f6-ffd91aedeb87'),
  ('0df95cbc-e81a-4137-aeb4-5054ea15aa1a'),
  ('7b6b8031-8b05-49e0-aa56-806a38fc9c61'),
  ('f35af199-56fd-4327-8fba-5ec6fbd5f833'),
  ('d9106c5f-0a37-4087-a1ee-466f190cc5f8'),
  ('202d802a-e956-448d-afab-41d42af37d77'),
  ('f19c308d-c276-493d-83a9-ced8d7de0520'),
  ('50659696-db17-47e9-9d42-d6c5e7630993'),
  ('f5180c27-45aa-40fd-afa8-3705a70c1e8d'),
  ('f04f67a1-f80a-47aa-953e-73e5e6d2775d'),
  ('9153fed5-088e-48bc-9bb0-70f2c1477ca2'),
  ('6be4d62e-139d-4a15-bae9-7d4c9732ac54'),
  ('7bfbdc3d-f827-4c53-808c-f39c0ba0e960'),
  ('14bb9679-aa26-4e63-a755-04f2da40d0f5'),
  ('a570e743-3982-45c9-a7f4-40fcb1dac749'),
  ('5a366340-a6ac-45d3-af84-8ec10cfa367d'),
  ('207ec239-fb00-46d2-8eaf-12aa4d71ad13'),
  ('05e24026-0d61-41cc-bf06-d3d32d4793f8'),
  ('7f6787cf-878c-4a4b-b7d3-2147e090358b'),
  ('6f99a080-ea73-40fe-bee8-f5afe70121d0'),
  ('9dbfc388-40d3-464e-994b-3dacc735dded'),
  ('6bdf409b-e086-41b5-9ff6-abe6af597032'),
  ('4998e3c1-620f-4fc7-9261-cfd9c9db13ad'),
  ('3f0ae99f-b73a-4d4c-9d9e-c353b0e95960'),
  ('429be2bd-44a4-4c38-bad1-30d604406de7'),
  ('ea17e614-fda7-4cb6-8bc8-77c451df9106'),
  ('0d3431c9-20a5-4c21-a7ea-b6a85e85345a'),
  ('f132337f-a83e-43de-b19a-25e96deb56a7'),
  ('25b8b090-82df-46ca-9f11-2dce11297f60'),
  ('41ae0b2c-9e4e-4f73-92ff-0893bd817c04'),
  ('da775640-771a-472a-abb6-36893c009dab'),
  ('dc662a2a-0c14-46e9-a917-34558fd3fa17'),
  ('02e10d7f-07e9-4c04-bba9-5ea1f434cbe8'),
  ('6434f443-73c4-476a-a8bc-0a91921c1820'),
  ('65318723-f5b4-4dfb-a825-3441367b1f16'),
  ('c98e723b-6bac-4963-b4f9-eb1d45c97671'),
  ('759a568f-dd66-46bd-8a3e-e026975f43c4'),
  ('522786b9-16e0-47a1-9196-012efdf60361'),
  ('1ab24d6c-8083-49cf-bb32-0df276f5cf52'),
  ('e3eb97d2-b0af-44f4-90e4-e74f49bcd478'),
  ('6b3d55b8-e5e7-4efe-9e33-bc3254198c8e'),
  ('ae0fe036-f2ec-43fe-abc0-7135f1700162'),
  ('3c7b541e-880f-428e-9804-3a17f7f6853b'),
  ('d6a7f9f5-8285-4cf4-9167-bfeee6f937bc'),
  ('eae34a9f-fc11-49ff-98b4-69fa00107095'),
  ('0bfa2fde-1ce6-4f91-9330-957382847efc'),
  ('90c53cff-e542-49d9-9292-36b3e929fc49'),
  ('9fb0483f-7ff0-4d16-97bf-b5d119b3e862'),
  ('89691df1-4949-47bc-aecf-7b624fea21c4'),
  ('83070d21-bb9c-4f11-9362-2f5f3e8e7f0b'),
  ('b916e771-7591-4d33-a59e-0d6157e5b227'),
  ('672283fc-bbf0-473d-80b1-c17ec17f6ce1'),
  ('618ff237-5904-466e-a136-3fd1b6545754'),
  ('eea8fc8e-6e68-4b2b-9eb5-e1c38dfa747e'),
  ('d18a6a5a-2b8c-4c5a-b191-c964f075e9b4'),
  ('46cb4d23-bafa-4df1-bf31-4fe41c32f721'),
  ('554c6edf-e852-4864-9eab-0a9ccfd2e8c1'),
  ('869a86be-690c-4a79-8d8f-6b82ca0a4a88'),
  ('89a370f9-6493-45d1-a46f-cd0be6dd6263'),
  ('94b2d254-5bcf-461e-9797-c84a81bad3f8'),
  ('0bb10884-c19f-4482-ab58-8974b4bc8206'),
  ('52ef1f41-e7d1-45c3-857e-378ff4bac32a'),
  ('91e725c3-9ebf-4f1a-8f86-db1ff17226cb'),
  ('10ddb80c-971d-4197-9812-c31ca6242e9f'),
  ('c6024f4a-ed58-4478-bf43-a2ac38ab99f8'),
  ('5320c7be-0074-4710-9771-2d5566d3024b'),
  ('f8ccb7f8-e136-4c1d-a60e-8ef53b2fd94f'),
  ('46aa8158-2e40-4186-90fe-8de89db1443f'),
  ('bf648722-ee2a-4a6f-9dac-7407b7917094'),
  ('24838019-ac72-4de9-b0f2-922cf1debabe'),
  ('19875a07-657b-4a69-bf37-e2122953aa31'),
  ('c3e512bf-5a7c-4622-92e0-fce04eda4697'),
  ('38a4b81b-2b2a-429d-8712-4d0cceacf1c4'),
  ('6029ad58-c7e3-4949-9821-048e11df1b60'),
  ('ed2d2b12-ade1-4d85-a8e4-25989bda768d'),
  ('d7538763-5b96-406f-bc93-b13d5eff6f3c'),
  ('48c636a6-b4df-46b5-b722-77c3ec5195ef'),
  ('dec5e996-ffbf-44e9-b2ee-6989240710c3'),
  ('170ead1b-b6b6-4d95-b109-9b9d1ea9e251'),
  ('cfae8f58-2bcf-4624-9029-3ceb822ed7af'),
  ('a0217b7c-cede-45c2-a20e-6873f7c63d62'),
  ('37e08979-2fc5-4175-ad1c-b3f70516716f'),
  ('8a1c4098-e77e-434e-a9e6-e2b1f5e71e71'),
  ('9b888c50-c447-4538-976c-ee7735591e9e'),
  ('b9c18e0f-749c-4409-b069-6f9c7213b78e'),
  ('20f185f7-8e40-42e1-8d0c-b1cc2598d145'),
  ('bf31cd44-4ca6-4e03-9c85-69e40bc715a5'),
  ('0ef71662-98ab-41b2-b2e7-17a880d07255'),
  ('066cc54f-db0d-475d-bc7c-6b3be950f1e7'),
  ('c2b95442-6cd9-4d21-8c15-be0d1a6f8fae'),
  ('edf31b04-88c4-45fd-80eb-f9c462c9d0c8'),
  ('53ba2186-2cb7-4fdd-a323-6558117480d4'),
  ('60ae4120-f607-4c3d-888c-9af3425eed7b'),
  ('619db2dc-ee4c-4128-85d5-6fd5a1b6d33f'),
  ('4a65bc86-42ac-4633-9ca4-cdb24c1baaee'),
  ('5a3a76b1-680c-4ee9-9340-f2a78ab9efeb'),
  ('6adbc86d-14a8-4a3b-8922-23e0aaa6dc6e'),
  ('ce28aadb-8b7d-4b01-b98a-69e95dfc6306'),
  ('23dfd92d-c713-406a-a1f2-66310b6b470c'),
  ('57b67255-8806-48af-8307-195f3a7a6a8f'),
  ('ad5bd1b5-737b-4786-9a2e-e81a8736197a'),
  ('67ff576c-8f78-4049-b0ef-240fbb551cd6'),
  ('94d21b5d-242d-4fe9-9e7b-9b1df6e5f22c'),
  ('04548ac2-a9ab-40b9-a968-9d588084feca'),
  ('ceb1ec98-d1a4-47b9-ac00-68dceb83f47a'),
  ('295bc6ba-0583-46aa-8d90-f8e51749eacc'),
  ('ac96988f-2b85-4736-96d8-a415bd57eb64'),
  ('4365fc69-442f-4b97-bb77-c7a5ec09ceee'),
  ('43e67d26-d57d-4079-a666-3195bda7c71a'),
  ('65d31cd1-5020-494e-b237-8bae31a81e36'),
  ('c3113b05-b291-4057-8bd6-932711cf8818'),
  ('4027546e-703c-4fe3-9820-ef06b97b5cc8'),
  ('2aebad67-2955-4c24-9a4a-c3924ec826cd'),
  ('5a3f3bf5-6f9c-4d1b-82cd-aedb00567544'),
  ('e80e1590-05b4-442b-995f-7025bd9db9e8'),
  ('3cc0cf08-b631-4929-9a34-ffb5b5d8fdc4'),
  ('42a0bc2b-e615-4e3f-8aee-b1eed4f9a71c'),
  ('da77bdf8-b3d2-4ded-ba39-b2a8250d1385'),
  ('d3b8c650-c308-4023-a56b-c35d350af0ab'),
  ('1902cff3-f576-42a7-b5b8-0393926e42b2'),
  ('11d07f24-8f46-44eb-8dab-3e39c70a4683'),
  ('f370af79-2179-4b48-ba2a-98cd33d85f8b'),
  ('df8abdca-64b4-4028-9893-48e581dae481'),
  ('ec905a23-487f-414f-8b0f-ba230fe5208e'),
  ('b11bd05a-167d-41ce-898b-0fd314d35796'),
  ('080aa7cd-9693-40df-82bd-c2af9e6671b9'),
  ('764afa7b-fb47-4a72-bee5-002421d5482c'),
  ('85cfd672-4194-467c-b898-ea1714f21e56'),
  ('2e76aed5-fbf6-4595-bb1f-118580071dff'),
  ('35a938fb-bea5-4e83-b6f1-347914f01e07'),
  ('001027e8-ef5f-4de9-8caa-89e695490a91'),
  ('60364a5f-2841-4358-81a6-bc375a23fd71'),
  ('dcd5c700-482a-4038-bba1-54f9d383e096'),
  ('559b31af-33d4-4be2-ba24-3d0e78f5d88c'),
  ('15de3022-f0f9-4e18-8277-72b672095f1e'),
  ('2f073b05-824e-41c4-b79c-626d390c2080'),
  ('9c7fe7c7-f89e-4654-b3a7-3cbcab844f67'),
  ('0bd61b52-37d0-4a52-bcca-51bf81d33398'),
  ('f369699f-4d91-42bb-a501-2c20e4321c2d'),
  ('f898cbf3-6d21-405e-8454-94bf626b6e03'),
  ('14690e3a-ce09-43f8-8036-98279ef43a4d'),
  ('6a841a20-09ca-4f46-b56d-59837a0be54d'),
  ('dfb6f248-0d1c-4bc2-8446-2a6b4ae457d8'),
  ('795acc7c-5e41-4527-bfce-2d074b817c87')
) AS curated(bout_id) ON b.id = curated.bout_id::uuid
ON CONFLICT (bout_id) DO NOTHING;

DROP VIEW IF EXISTS fighter_vertex_score CASCADE;

CREATE VIEW fighter_vertex_score AS
WITH
ufc_record AS (
  SELECT
    f.id AS fighter_id,
    COUNT(*) FILTER (WHERE b.status = 'completed') AS ufc_bouts,
    COUNT(*) FILTER (WHERE b.winner_id = f.id AND b.status = 'completed') AS ufc_wins,
    COUNT(*) FILTER (
      WHERE b.status = 'completed'
        AND b.winner_id IS NOT NULL
        AND b.winner_id <> f.id
    ) AS ufc_losses,
    MAX(e.date) FILTER (WHERE b.status = 'completed') AS last_fight_date
  FROM fighter f
  LEFT JOIN bout b
    ON (b.fighter_a_id = f.id OR b.fighter_b_id = f.id)
  LEFT JOIN event e ON e.id = b.event_id
  GROUP BY f.id
),
ranked_bouts AS (
  SELECT
    f.id AS f_id,
    b.winner_id,
    e.date AS event_date,
    ROW_NUMBER() OVER (
      PARTITION BY f.id
      ORDER BY e.date DESC, b.id DESC
    ) AS rn_desc
  FROM fighter f
  JOIN bout b ON (b.fighter_a_id = f.id OR b.fighter_b_id = f.id)
  JOIN event e ON e.id = b.event_id
  WHERE b.status = 'completed'
),
-- Wave 31: most-recent-bout flag for the fresh-loss penalty branch in the
-- final SELECT. is_loss when the latest completed bout (rn_desc=1) has a
-- winner that isn't the fighter. No-contests (winner_id NULL) → FALSE.
most_recent_bout AS (
  SELECT
    f_id AS fighter_id,
    (winner_id IS NOT NULL AND winner_id <> f_id) AS most_recent_is_loss
  FROM ranked_bouts
  WHERE rn_desc = 1
),
recent_losses AS (
  SELECT
    f_id AS fighter_id,
    COUNT(*) FILTER (
      WHERE rn_desc <= 3 AND winner_id IS NOT NULL AND winner_id <> f_id
    )::int AS losses_last_3,
    COUNT(*) FILTER (
      WHERE rn_desc <= 5 AND winner_id IS NOT NULL AND winner_id <> f_id
    )::int AS losses_last_5,
    COUNT(*) FILTER (
      WHERE event_date > NOW() - INTERVAL '24 months'
        AND winner_id IS NOT NULL AND winner_id <> f_id
    )::int AS losses_24mo
  FROM ranked_bouts
  GROUP BY f_id
),
recent_losses_weighted AS (
  SELECT
    f.id AS fighter_id,
    e.date AS bout_date,
    (b.winner_id IS NOT NULL AND b.winner_id <> f.id) AS is_loss,
    LEAST(1.0, GREATEST(0.6,
      1.0 - COALESCE(bot.opp_tier_value, 0)::float / 30.0
    )) AS severity,
    ROW_NUMBER() OVER (
      PARTITION BY f.id
      ORDER BY e.date DESC, b.id DESC
    ) AS rn_desc
  FROM fighter f
  JOIN bout b ON (b.fighter_a_id = f.id OR b.fighter_b_id = f.id)
  JOIN event e ON e.id = b.event_id
  LEFT JOIN bout_opponent_tier bot
    ON bot.bout_id = b.id AND bot.fighter_id = f.id
  WHERE b.status = 'completed'
),
recent_loss_penalty_calc AS (
  SELECT
    fighter_id,
    LEAST(100, ROUND(
        COALESCE(SUM(severity) FILTER (WHERE is_loss AND rn_desc <= 3), 0) * 25
      + COALESCE(SUM(severity) FILTER (WHERE is_loss AND rn_desc <= 5), 0) * 12
      + COALESCE(SUM(severity) FILTER (
          WHERE is_loss AND bout_date >= NOW() - INTERVAL '24 months'
        ), 0) * 6
    ))::int AS recent_loss_penalty
  FROM recent_losses_weighted
  GROUP BY fighter_id
),
control_time_per_fighter AS (
  SELECT
    brs.fighter_id,
    SUM(brs.control_time_seconds)::float AS total_control_seconds,
    SUM(CASE
      WHEN brs.round < b.round_finished THEN 300
      WHEN brs.round = b.round_finished THEN b.time_finished_seconds
      ELSE 0
    END)::float AS total_fight_seconds
  FROM bout_round_stats brs
  JOIN bout b ON b.id = brs.bout_id
  WHERE b.status = 'completed'
  GROUP BY brs.fighter_id
),
performance_diff AS (
  SELECT
    fsa.fighter_id,
    LEAST(100, GREATEST(0, ROUND(
        0.45 * (50 + (COALESCE(fsa.slpm, 0)::float - COALESCE(fsa.sapm, 0)::float) * 20.0)
      + 0.35 * (
          CASE
            WHEN ctp.total_fight_seconds IS NULL OR ctp.total_fight_seconds = 0 THEN 50
            ELSE LEAST(100, GREATEST(0,
              50 + ((ctp.total_control_seconds / ctp.total_fight_seconds * 60.0) - 15.0) * 2.6
            ))
          END
        )
      + 0.20 * (50 + (
          COALESCE(fsa.td_avg, 0)::float
          - (1.0 - COALESCE(fsa.td_def, 0.5)::float) * 3.0
        ) * 20.0)
    ))) AS performance_diff_score
  FROM fighter_stats_aggregate fsa
  LEFT JOIN control_time_per_fighter ctp ON ctp.fighter_id = fsa.fighter_id
),
finishing_dom AS (
  SELECT
    f.id AS fighter_id,
    COALESCE(SUM(brs.knockdowns), 0)::float   AS total_kd,
    COALESCE(SUM(brs.sub_attempts), 0)::float AS total_sa,
    COALESCE(SUM(CASE
      WHEN brs.round < b.round_finished THEN 300
      WHEN brs.round = b.round_finished THEN b.time_finished_seconds
      ELSE 0
    END), 0)::float AS total_seconds,
    COUNT(DISTINCT b.id) FILTER (
      WHERE b.winner_id = f.id
        AND (
          LOWER(COALESCE(b.method::text, '')) LIKE 'ko%'
          OR LOWER(COALESCE(b.method::text, '')) LIKE 'tko%'
          OR (b.method IS NULL AND COALESCE(brs.knockdowns, 0) > 0)
        )
    )::float AS ko_wins_count,
    COUNT(DISTINCT b.id) FILTER (
      WHERE b.winner_id = f.id
        AND (
          LOWER(COALESCE(b.method::text, '')) LIKE 'sub%'
          OR (b.method IS NULL AND COALESCE(brs.sub_attempts, 0) > 0)
        )
    )::float AS sub_wins_count,
    COUNT(DISTINCT b.id) FILTER (
      WHERE b.winner_id = f.id
        AND (
          LOWER(COALESCE(b.method::text, '')) LIKE 'ko%'
          OR LOWER(COALESCE(b.method::text, '')) LIKE 'tko%'
          OR (b.method IS NULL AND COALESCE(brs.knockdowns, 0) > 0)
        )
    )::float
      / NULLIF(
          COUNT(DISTINCT b.id) FILTER (WHERE b.winner_id = f.id),
          0
        ) AS ko_rate,
    COUNT(DISTINCT b.id) FILTER (
      WHERE b.winner_id = f.id
        AND (
          LOWER(COALESCE(b.method::text, '')) LIKE 'sub%'
          OR (b.method IS NULL AND COALESCE(brs.sub_attempts, 0) > 0)
        )
    )::float
      / NULLIF(
          COUNT(DISTINCT b.id) FILTER (WHERE b.winner_id = f.id),
          0
        ) AS sub_rate
  FROM fighter f
  LEFT JOIN bout b
    ON (b.fighter_a_id = f.id OR b.fighter_b_id = f.id)
    AND b.status = 'completed'
  LEFT JOIN bout_round_stats brs
    ON brs.bout_id = b.id
   AND brs.fighter_id = f.id
  GROUP BY f.id
),
bout_fighter_stats AS (
  SELECT
    brs.bout_id,
    brs.fighter_id,
    SUM(brs.sig_str_landed)::int          AS sig_str_landed_total,
    SUM(brs.control_time_seconds)::int    AS control_seconds_total,
    SUM(brs.takedowns_landed)::int        AS takedowns_landed_total,
    SUM(brs.knockdowns)::int              AS knockdowns_total,
    SUM(brs.sub_attempts)::int            AS sub_attempts_total
  FROM bout_round_stats brs
  GROUP BY brs.bout_id, brs.fighter_id
),
recent_bouts_window AS (
  SELECT
    bf.bout_id,
    bf.fighter_id,
    (b.winner_id = bf.fighter_id) AS is_win,
    e.date AS bout_date,
    b.method::text AS method,
    CASE
      WHEN b.round_finished IS NULL THEN COALESCE(b.scheduled_rounds, 3) * 300
      ELSE (b.round_finished - 1) * 300 + COALESCE(b.time_finished_seconds, 300)
    END AS bout_fight_seconds,
    COALESCE(bot.opp_tier_value, 0) AS opp_tier_value,
    COALESCE(bfs.sig_str_landed_total, 0)        AS sig_landed,
    COALESCE(bfs_opp.sig_str_landed_total, 0)    AS sig_absorbed,
    COALESCE(bfs.control_seconds_total, 0)       AS control_seconds,
    COALESCE(bfs.takedowns_landed_total, 0)      AS td_landed,
    COALESCE(bfs_opp.takedowns_landed_total, 0)  AS opp_td_landed,
    COALESCE(bfs.knockdowns_total, 0)            AS kd_total,
    COALESCE(bfs.sub_attempts_total, 0)          AS sa_total,
    ROW_NUMBER() OVER (
      PARTITION BY bf.fighter_id
      ORDER BY e.date DESC, b.id DESC
    ) AS recency_rank
  FROM (
    SELECT id AS bout_id, fighter_a_id AS fighter_id, fighter_b_id AS opp_id
    FROM bout WHERE status = 'completed'
    UNION ALL
    SELECT id AS bout_id, fighter_b_id AS fighter_id, fighter_a_id AS opp_id
    FROM bout WHERE status = 'completed'
  ) bf
  JOIN bout b ON b.id = bf.bout_id
  JOIN event e ON e.id = b.event_id
  LEFT JOIN bout_opponent_tier bot
    ON bot.bout_id = bf.bout_id AND bot.fighter_id = bf.fighter_id
  LEFT JOIN bout_fighter_stats bfs
    ON bfs.bout_id = bf.bout_id AND bfs.fighter_id = bf.fighter_id
  LEFT JOIN bout_fighter_stats bfs_opp
    ON bfs_opp.bout_id = bf.bout_id AND bfs_opp.fighter_id = bf.opp_id
),
recent_performance AS (
  SELECT
    fighter_id,
    COUNT(*) AS recent_bout_count,
    AVG(
      LEAST(100, GREATEST(0,
        50 + ((sig_landed - sig_absorbed)::float * 60.0 / NULLIF(bout_fight_seconds, 0)) * 20.0
      ))
    ) AS recent_striking_dominance,
    AVG(
      CASE
        WHEN bout_fight_seconds = 0 THEN 50.0
        ELSE LEAST(100, GREATEST(0,
          50 + ((control_seconds::float / NULLIF(bout_fight_seconds, 0) * 60.0) - 15.0) * 2.6
        ))
      END
    ) AS recent_control_dominance,
    AVG(
      LEAST(100, GREATEST(0,
        50 + ((td_landed - opp_td_landed)::float * 900.0 / NULLIF(bout_fight_seconds, 0)) * 5.0
      ))
    ) AS recent_td_dominance,
    AVG(
      LEAST(100, GREATEST(0,
        50 + ((sig_landed - sig_absorbed)::float * 60.0 / NULLIF(bout_fight_seconds, 0)) * 20.0
      )) - LEAST(90.0, 50.0 + (50.0 - LEAST(50.0, opp_tier_value::float * 2.0)))
    ) AS recent_adjusted_delta
  FROM recent_bouts_window
  WHERE recency_rank <= 5
  GROUP BY fighter_id
),
recent_performance_dims AS (
  SELECT
    fighter_id,
    recent_bout_count,
    LEAST(100.0, GREATEST(0.0,
      COALESCE(recent_striking_dominance, 50) + COALESCE(recent_adjusted_delta, 0) * 0.5
    ))::float AS striking_diff_score,
    LEAST(100.0, GREATEST(0.0,
      COALESCE(recent_control_dominance, 50) + COALESCE(recent_adjusted_delta, 0) * 0.3
    ))::float AS control_diff_score,
    LEAST(100.0, GREATEST(0.0,
      COALESCE(recent_td_dominance, 50)
    ))::float AS td_diff_score
  FROM recent_performance
),
-- Wave 31: recency-weighted recent_form_score. Each of the 5 most recent
-- bouts contributes weighted by rn_desc (rn=1 → 2.0, rn=5 → 0.5). The new
-- output is the weighted mean × 1.5 + 50, which equals the Wave 15 formula
-- exactly when all 5 contributions are equal but bites the most recent
-- loss harder than the oldest one.
-- Wave 55: scorecard margin per (bout, fighter). SUM over every
-- (judge, round) cell, ÷ judges ÷ rounds = margin per round. A 30-27
-- sweep or a 50-45 = 1.0/round; a 10-8 round lifts it; a split dips
-- toward 0. ~81% of decision bouts have mmadecisions.com scorecards.
scorecard_margin AS (
  SELECT
    sc.bout_id,
    side.fighter_id,
    (
      SUM(
        CASE WHEN side.is_a
          THEN sc.fighter_a_score - sc.fighter_b_score
          ELSE sc.fighter_b_score - sc.fighter_a_score
        END
      )::float
      / NULLIF(COUNT(DISTINCT sc.judge_name), 0)
      / NULLIF(COUNT(DISTINCT sc.round), 0)
    ) AS margin_per_round
  FROM bout_scorecard sc
  JOIN bout b ON b.id = sc.bout_id
  CROSS JOIN LATERAL (VALUES
    (b.fighter_a_id, TRUE),
    (b.fighter_b_id, FALSE)
  ) AS side(fighter_id, is_a)
  GROUP BY sc.bout_id, side.fighter_id, side.is_a
),
recent_form AS (
  WITH bout_contributions AS (
    SELECT
      rbw.fighter_id,
      rbw.recency_rank,
      CASE
        WHEN rbw.is_win IS NULL THEN 0
        WHEN rbw.method IS NOT NULL
          AND LOWER(rbw.method) LIKE '%no_contest%' THEN 0
        WHEN rbw.is_win THEN rbw.opp_tier_value::float * (
          -- Wave 55: win-quality — finish 1.15; decision scaled
          -- 0.90 (razor split) .. 1.10 (blowout) by scorecard
          -- margin/round; decision with no scorecard → 1.00.
          CASE
            WHEN LOWER(COALESCE(rbw.method, '')) LIKE 'ko%'
              OR LOWER(COALESCE(rbw.method, '')) LIKE 'tko%'
              OR LOWER(COALESCE(rbw.method, '')) LIKE 'sub%' THEN 1.15
            WHEN sm.margin_per_round IS NULL THEN 1.00
            ELSE 0.90 + 0.10 * LEAST(2.0, GREATEST(0.0, sm.margin_per_round))
          END
        )
        ELSE -(rbw.opp_tier_value::float) *
          CASE
            WHEN rbw.opp_tier_value >= 25 THEN 0.30
            WHEN rbw.opp_tier_value >= 22 THEN 0.45
            WHEN rbw.opp_tier_value >= 14 THEN 0.60
            WHEN rbw.opp_tier_value >= 8  THEN 0.75
            WHEN rbw.opp_tier_value >= 3  THEN 0.90
            ELSE 1.00
          END
      END AS contribution,
      CASE rbw.recency_rank
        WHEN 1 THEN 2.00
        WHEN 2 THEN 1.50
        WHEN 3 THEN 1.00
        WHEN 4 THEN 0.75
        WHEN 5 THEN 0.50
        ELSE 0.00
      END::float AS recency_weight
    FROM recent_bouts_window rbw
    LEFT JOIN scorecard_margin sm
      ON sm.bout_id = rbw.bout_id AND sm.fighter_id = rbw.fighter_id
    WHERE rbw.recency_rank <= 5
  )
  SELECT
    fighter_id,
    LEAST(100, GREATEST(0, ROUND(
      50.0
      + (SUM(contribution * recency_weight) / NULLIF(SUM(recency_weight), 0))
        * 1.50
    )))::int AS recent_form_score,
    COUNT(*) AS recent_bout_count
  FROM bout_contributions
  GROUP BY fighter_id
),
months_since_last AS (
  SELECT
    ur.fighter_id,
    CASE
      WHEN ur.last_fight_date IS NULL THEN NULL
      ELSE EXTRACT(EPOCH FROM (NOW() - ur.last_fight_date)) / (60.0 * 60 * 24 * 30.4375)
    END AS m
  FROM ufc_record ur
),
recent_title_fight_counts AS (
  SELECT
    f.id AS fighter_id,
    COUNT(*) FILTER (
      WHERE e.date >= NOW() - INTERVAL '24 months'
    )::int AS tf_24mo,
    COUNT(*) FILTER (
      WHERE e.date >= NOW() - INTERVAL '36 months'
    )::int AS tf_36mo
  FROM fighter f
  -- Wave 60: curated title fights (title_fight_bout) — the scraped
  -- is_title_fight flag over-counts (bonus icons share the belt cell).
  LEFT JOIN bout b
    ON (b.fighter_a_id = f.id OR b.fighter_b_id = f.id)
    AND b.status = 'completed'
    AND EXISTS (SELECT 1 FROM title_fight_bout tfb WHERE tfb.bout_id = b.id)
  LEFT JOIN event e ON e.id = b.event_id
  GROUP BY f.id
),
bout_decay AS (
  SELECT
    f.id AS fighter_id,
    b.id AS bout_id,
    e.date AS bout_date,
    (b.winner_id = f.id) AS is_win,
    (
      LOWER(COALESCE(b.method::text, '')) LIKE 'ko%'
      OR LOWER(COALESCE(b.method::text, '')) LIKE 'tko%'
      OR LOWER(COALESCE(b.method::text, '')) LIKE 'sub%'
      OR (b.method IS NULL AND COALESCE(bfs.knockdowns_total, 0) > 0)
      OR (b.method IS NULL AND COALESCE(bfs.sub_attempts_total, 0) > 0)
    ) AS is_finish_method,
    COALESCE(bot.opp_tier_value, 0) AS opp_tier_value,
    GREATEST(0.1, LEAST(1.0,
      CASE
        WHEN (EXTRACT(EPOCH FROM (NOW() - e.date)) / (365.25 * 86400)) <= 1.0 THEN 1.0
        WHEN (EXTRACT(EPOCH FROM (NOW() - e.date)) / (365.25 * 86400)) <= 3.0 THEN
          1.0 - 0.7 * ((EXTRACT(EPOCH FROM (NOW() - e.date)) / (365.25 * 86400)) - 1.0) / 2.0
        WHEN (EXTRACT(EPOCH FROM (NOW() - e.date)) / (365.25 * 86400)) <= 5.0 THEN
          0.3 - 0.2 * ((EXTRACT(EPOCH FROM (NOW() - e.date)) / (365.25 * 86400)) - 3.0) / 2.0
        ELSE 0.1
      END
    ))::float AS decay_factor
  FROM fighter f
  JOIN bout b ON (b.fighter_a_id = f.id OR b.fighter_b_id = f.id)
  JOIN event e ON e.id = b.event_id
  LEFT JOIN bout_opponent_tier bot ON bot.bout_id = b.id AND bot.fighter_id = f.id
  LEFT JOIN bout_fighter_stats bfs ON bfs.bout_id = b.id AND bfs.fighter_id = f.id
  WHERE b.status = 'completed'
),
quality_wins_decayed_calc AS (
  SELECT
    fighter_id,
    LEAST(100.0, COALESCE(
      SUM(opp_tier_value::float * decay_factor) FILTER (WHERE is_win),
      0
    ))::float AS quality_wins_decayed
  FROM bout_decay
  GROUP BY fighter_id
),
finishing_dom_decayed_calc AS (
  SELECT
    fighter_id,
    CASE
      WHEN COALESCE(
        SUM(decay_factor * GREATEST(opp_tier_value, 1)) FILTER (WHERE is_win),
        0
      ) = 0 THEN 0.0
      ELSE 100.0
        * COALESCE(
            SUM(decay_factor * GREATEST(opp_tier_value, 1))
              FILTER (WHERE is_win AND is_finish_method),
            0
          )
        / SUM(decay_factor * GREATEST(opp_tier_value, 1))
            FILTER (WHERE is_win)
    END::float AS finishing_dominance_decayed
  FROM bout_decay
  GROUP BY fighter_id
),
kd_received_calc AS (
  SELECT
    f.id AS fighter_id,
    COALESCE(SUM(brs.knockdowns), 0)::float AS total_kd_received,
    COUNT(DISTINCT b.id)::int AS bouts_counted,
    CASE
      WHEN COUNT(DISTINCT b.id) > 0 THEN
        COALESCE(SUM(brs.knockdowns), 0)::float / COUNT(DISTINCT b.id)::float
      ELSE 0.0
    END AS kd_received_per_fight
  FROM fighter f
  LEFT JOIN bout b
    ON (b.fighter_a_id = f.id OR b.fighter_b_id = f.id)
    AND b.status = 'completed'
  LEFT JOIN bout_round_stats brs
    ON brs.bout_id = b.id
    AND brs.fighter_id = CASE
      WHEN b.fighter_a_id = f.id THEN b.fighter_b_id
      ELSE b.fighter_a_id
    END
  GROUP BY f.id
),
defensive_vulnerability_calc AS (
  SELECT
    f.id AS fighter_id,
    LEAST(1.0, COALESCE(fsa.slpm, 0)::float / 5.0)::float AS striker_intent,
    LEAST(1.0, COALESCE(fsa.td_avg, 0)::float / 2.0)::float AS wrestler_intent,
    (GREATEST(0.0, 0.55 - COALESCE(fsa.td_def, 0.55)::float) / 0.55)::float
      AS td_def_weakness,
    (GREATEST(0.0, 0.55 - COALESCE(fsa.str_def, 0.55)::float) / 0.55)::float
      AS str_def_weakness,
    (LEAST(1.0, GREATEST(0.0, COALESCE(fsa.sapm, 0)::float - 4.0) / 4.0))::float
      AS sapm_weakness,
    (LEAST(1.0, GREATEST(0.0,
      COALESCE(kdr.kd_received_per_fight, 0.0) - 0.15
    ) / 0.25))::float AS kd_received_weakness
  FROM fighter f
  LEFT JOIN fighter_stats_aggregate fsa ON fsa.fighter_id = f.id
  LEFT JOIN kd_received_calc kdr ON kdr.fighter_id = f.id
),
defensive_vulnerability_score AS (
  SELECT
    fighter_id,
    LEAST(100.0, GREATEST(0.0,
      (
        striker_intent * td_def_weakness
        + wrestler_intent * (
            str_def_weakness * 0.45
          + sapm_weakness * 0.25
          + kd_received_weakness * 0.30
        )
      ) * 100.0
    ))::float AS defensive_vulnerability
  FROM defensive_vulnerability_calc
),
-- Wave 31: age curve. Computed once per fighter from dob. NULL dob → 0%
-- (neutral — we don't have a signal to apply). Floor over years to keep
-- the bucket boundaries clean across the year (a fighter who turns 35
-- mid-year crosses from +0% to -4% on their birthday, not gradually).
fighter_age_calc AS (
  SELECT
    f.id AS fighter_id,
    CASE
      WHEN f.dob IS NULL THEN NULL
      ELSE FLOOR(EXTRACT(EPOCH FROM (NOW() - f.dob)) / (365.25 * 86400))::int
    END AS age_years,
    CASE
      WHEN f.dob IS NULL THEN 0.00
      WHEN FLOOR(EXTRACT(EPOCH FROM (NOW() - f.dob)) / (365.25 * 86400)) < 26 THEN 0.00
      WHEN FLOOR(EXTRACT(EPOCH FROM (NOW() - f.dob)) / (365.25 * 86400)) <= 30 THEN  0.05
      WHEN FLOOR(EXTRACT(EPOCH FROM (NOW() - f.dob)) / (365.25 * 86400)) <= 32 THEN  0.02
      WHEN FLOOR(EXTRACT(EPOCH FROM (NOW() - f.dob)) / (365.25 * 86400)) <= 34 THEN  0.00
      WHEN FLOOR(EXTRACT(EPOCH FROM (NOW() - f.dob)) / (365.25 * 86400)) <= 36 THEN -0.04
      WHEN FLOOR(EXTRACT(EPOCH FROM (NOW() - f.dob)) / (365.25 * 86400)) <= 38 THEN -0.08
      ELSE -0.12
    END::float AS age_factor
  FROM fighter f
),
components AS (
  SELECT
    f.id,
    f.slug,
    f.is_dominant_champion,
    f.roster_status,
    f.has_upcoming_bout,
    COALESCE(ur.ufc_bouts, 0) AS ufc_bouts,
    COALESCE(ur.ufc_wins, 0) AS ufc_wins,
    COALESCE(ur.ufc_losses, 0) AS ufc_losses,
    ur.last_fight_date,

    (f.roster_status = 'active'
     OR (ur.last_fight_date IS NOT NULL
         AND ur.last_fight_date > NOW() - INTERVAL '24 months')) AS is_active,

    COALESCE(rl.losses_last_3, 0) AS losses_last_3,
    COALESCE(rl.losses_last_5, 0) AS losses_last_5,
    COALESCE(rl.losses_24mo, 0) AS losses_24mo,

    -- Wave 31: surface most_recent_is_loss for the fresh-loss CASE branch
    -- in the final SELECT. FALSE for fighters with zero completed bouts.
    COALESCE(mrb.most_recent_is_loss, FALSE) AS most_recent_is_loss,

    COALESCE(f.quality_wins_score, 0)::float AS quality_wins,
    COALESCE(qwd.quality_wins_decayed, 0)::float AS quality_wins_decayed,

    COALESCE(f.championship_pedigree, 0)::float AS championship_pedigree,
    COALESCE(f.current_cp, 0)::float AS current_cp,

    -- Wave 60: 0-100 parity (was 0-10). Title fight in 24mo → 50,
    -- ≥2 title fights in 36mo → +50. Same signal, ×10 scale — at the
    -- unchanged 0.06 weight the component now contributes up to 6.0
    -- raw points (was 0.6), in line with its 0-100-scale neighbours.
    LEAST(100,
      (CASE WHEN COALESCE(rtfc.tf_24mo, 0) >= 1 THEN 50 ELSE 0 END)
    + (CASE WHEN COALESCE(rtfc.tf_36mo, 0) >= 2 THEN 50 ELSE 0 END)
    )::float AS era_dominance_current,
    COALESCE(f.era_dominance_all_time, 0)::float AS era_dominance_all_time,

    COALESCE(f.apex_wins, 0) AS apex_wins,
    COALESCE(f.strong_wins, 0) AS strong_wins,
    COALESCE(f.solid_wins, 0) AS solid_wins,
    COALESCE(f.legacy_wins, 0) AS legacy_wins,
    COALESCE(f.ranked_wins, 0) AS ranked_wins,
    COALESCE(f.top5_wins, 0) AS top5_wins,
    COALESCE(f.top10_wins, 0) AS top10_wins,
    COALESCE(f.top15_wins, 0) AS top15_wins,
    COALESCE(f.title_fight_count, 0) AS title_fight_count,
    COALESCE(f.current_streak, 0) AS current_streak,
    (COALESCE(rtfc.tf_24mo, 0) >= 1) AS had_title_fight_recently,

    COALESCE(rfm.recent_form_score, 50)::int AS recent_form_score,

    GREATEST(
      LEAST(100.0,
        COALESCE(f.fights_last_12mo, 0)::float
        * COALESCE(f.avg_opp_tier_last_12mo, 0)::float / 60.0 * 100.0
      ),
      LEAST(100.0,
        COALESCE(f.fights_last_24mo, 0)::float
        * COALESCE(f.avg_opp_tier_last_24mo, 0)::float / 120.0 * 100.0
      ),
      LEAST(100.0,
        COALESCE(f.fights_last_36mo, 0)::float
        * COALESCE(f.avg_opp_tier_last_36mo, 0)::float / 180.0 * 100.0
      )
    )::float AS activity,

    COALESCE(rlp.recent_loss_penalty, 0)::float AS recent_loss_penalty,

    -- Wave 53: opp-tier-weighted all-time loss penalty. Each loss
    -- costs 4 × severity, severity = LEAST(1, GREATEST(0.35,
    -- 1 - opp_tier/30)) — a loss to a champion ≈ 1.4, a loss to a
    -- journeyman ≈ 4. Replaces the flat ufc_losses × 4.
    LEAST(100, COALESCE((
      SELECT ROUND(SUM(
        4.0 * LEAST(1.0, GREATEST(0.35,
          1.0 - COALESCE(bot_atl.opp_tier_value, 0)::float / 30.0
        ))
      ))
      FROM bout b_atl
      LEFT JOIN bout_opponent_tier bot_atl
        ON bot_atl.bout_id = b_atl.id AND bot_atl.fighter_id = f.id
      WHERE (b_atl.fighter_a_id = f.id OR b_atl.fighter_b_id = f.id)
        AND b_atl.status = 'completed'
        AND b_atl.winner_id IS NOT NULL
        AND b_atl.winner_id <> f.id
    ), 0))::float AS total_loss_penalty,
    -- Wave 53: career peak — highest replayed vertex_score from
    -- fighter_score_history (Wave 31.7). Feeds the all-time formula.
    COALESCE((
      SELECT MAX(fsh.vertex_score)
      FROM fighter_score_history fsh
      WHERE fsh.fighter_id = f.id
    ), 0)::float AS peak_career,

    COALESCE(pd.performance_diff_score, 50)::float AS performance_diff,

    CASE
      WHEN rpd.recent_bout_count IS NULL OR rpd.recent_bout_count = 0 THEN 50.0
      ELSE LEAST(100.0,
        GREATEST(rpd.striking_diff_score, rpd.control_diff_score, rpd.td_diff_score)
        * (
          1.0
          + 0.25
            * LEAST(rpd.striking_diff_score, rpd.control_diff_score, rpd.td_diff_score)
              / GREATEST(GREATEST(rpd.striking_diff_score, rpd.control_diff_score, rpd.td_diff_score), 1.0)
        )
      )
    END::float AS performance_diff_current,

    LEAST(100, GREATEST(0,
      CASE
        WHEN COALESCE(fd.total_seconds, 0) > 0 THEN
          (fd.total_kd / fd.total_seconds * 900.0) * 10.0
        + (fd.total_sa / fd.total_seconds * 900.0) * 10.0
        + (COALESCE(fd.ko_wins_count, 0) / fd.total_seconds * 900.0) * 20.0
        + (COALESCE(fd.sub_wins_count, 0) / fd.total_seconds * 900.0) * 100.0
        ELSE 0
      END
      + COALESCE(fd.ko_rate, 0) * 25.0
      + COALESCE(fd.sub_rate, 0) * 25.0
    ))::float AS finishing_dominance_score,

    COALESCE(fdd.finishing_dominance_decayed, 0)::float AS finishing_dominance_decayed,

    COALESCE(dvs.defensive_vulnerability, 0)::float AS defensive_vulnerability,

    -- Wave 31: surface age + layoff signals for raw_scores and for
    -- diagnostic output.
    fac.age_years,
    COALESCE(fac.age_factor, 0.0)::float AS age_factor,
    msl.m::float AS months_since_last,
    -- layoff_penalty surfaced as its own column so the materialize script
    -- and downstream debuggers can see it cleanly without re-deriving.
    CASE
      WHEN msl.m IS NULL OR msl.m <= 12 THEN 0.0
      ELSE LEAST(15.0, (msl.m - 12.0) * 0.5)
    END::float AS layoff_penalty

  FROM fighter f
  LEFT JOIN ufc_record ur ON ur.fighter_id = f.id
  LEFT JOIN recent_losses rl ON rl.fighter_id = f.id
  LEFT JOIN most_recent_bout mrb ON mrb.fighter_id = f.id
  LEFT JOIN recent_loss_penalty_calc rlp ON rlp.fighter_id = f.id
  LEFT JOIN performance_diff pd ON pd.fighter_id = f.id
  LEFT JOIN finishing_dom fd ON fd.fighter_id = f.id
  LEFT JOIN recent_performance rp ON rp.fighter_id = f.id
  LEFT JOIN recent_performance_dims rpd ON rpd.fighter_id = f.id
  LEFT JOIN recent_form rfm ON rfm.fighter_id = f.id
  LEFT JOIN months_since_last msl ON msl.fighter_id = f.id
  LEFT JOIN recent_title_fight_counts rtfc ON rtfc.fighter_id = f.id
  LEFT JOIN quality_wins_decayed_calc qwd ON qwd.fighter_id = f.id
  LEFT JOIN finishing_dom_decayed_calc fdd ON fdd.fighter_id = f.id
  LEFT JOIN defensive_vulnerability_score dvs ON dvs.fighter_id = f.id
  LEFT JOIN fighter_age_calc fac ON fac.fighter_id = f.id
),
raw_scores AS (
  SELECT
    *,
    -- Wave 31: layoff term subtracted alongside other penalties, then the
    -- whole positive-minus-penalty sum is multiplied by (1 + age_factor).
    -- Age applies AFTER all penalties so a young fighter with bad form
    -- doesn't get artificially propped up and an old fighter with good
    -- form sees the decline appropriately. GREATEST(0, ...) on the inner
    -- sum keeps the multiplication monotonic when penalties dominate.
    CASE
      WHEN is_active AND ufc_bouts >= 5 THEN
        GREATEST(0,
          (
              quality_wins_decayed * 0.16
            + current_cp * 0.10
            + era_dominance_current * 0.06
            + performance_diff_current * 0.16
            + finishing_dominance_decayed * 0.10
            + activity * 0.12
            + recent_form_score::float * 0.18
            - recent_loss_penalty * 0.20
            - defensive_vulnerability * 0.10
            - layoff_penalty
            -- Wave 32: win-streak bonus (raw points, +0..5).
            + LEAST(5.0, GREATEST(0.0, current_streak - 2))
          ) * (1.0 + age_factor)
            -- Wave 54: credibility — current score is mildly
            -- damped for thin résumés (full credibility by 12
            -- UFC bouts, 0.85 floor).
            * LEAST(1.0, 0.85 + 0.15 * LEAST(1.0, ufc_bouts / 12.0))
        )
      ELSE NULL
    END AS raw_current
  FROM components
),
multiplied AS (
  SELECT
    *,
    -- Wave 31 re-anchored curve. Anchors: (0,0), (25,25), (45,60),
    -- (60,80), (75,93), (88,100). 100 reserved for raw ≥ 88, which
    -- requires near-perfect positives with zero penalties.
    CASE
      WHEN raw_current IS NULL THEN NULL
      WHEN raw_current >= 88 THEN 100
      WHEN raw_current >= 75 THEN
        LEAST(100, ROUND(93 + (raw_current - 75) * (7.0 / 13.0)))::int
      WHEN raw_current >= 60 THEN
        LEAST(100, ROUND(80 + (raw_current - 60) * (13.0 / 15.0)))::int
      WHEN raw_current >= 45 THEN
        LEAST(100, ROUND(60 + (raw_current - 45) * (20.0 / 15.0)))::int
      WHEN raw_current >= 25 THEN
        LEAST(100, ROUND(25 + (raw_current - 25) * (35.0 / 20.0)))::int
      ELSE
        GREATEST(0, ROUND(raw_current * 1.0))::int
    END AS multiplied_current
  FROM raw_scores
)
SELECT
  id,
  slug,
  ufc_bouts,
  ufc_wins,
  ufc_losses,
  last_fight_date,
  is_active,
  is_dominant_champion,
  roster_status,
  has_upcoming_bout,
  losses_last_3,
  losses_last_5,
  losses_24mo,
  most_recent_is_loss,
  apex_wins,
  strong_wins,
  solid_wins,
  legacy_wins,
  ranked_wins,
  top5_wins,
  top10_wins,
  top15_wins,
  title_fight_count,
  current_streak,
  recent_form_score,
  quality_wins,
  quality_wins_decayed,
  championship_pedigree,
  current_cp,
  era_dominance_current,
  era_dominance_all_time,
  had_title_fight_recently,
  performance_diff,
  performance_diff_current,
  finishing_dominance_score,
  finishing_dominance_decayed,
  activity,
  recent_loss_penalty,
  defensive_vulnerability,
  total_loss_penalty,
  peak_career,
  age_years,
  age_factor,
  months_since_last,
  layoff_penalty,
  raw_current,
  multiplied_current,

  -- Wave 31: stacked skid + fresh-loss penalty branches. Skid catches
  -- first (top-down), so the new fresh-loss branch only fires when a
  -- single recent loss didn't already trigger a heavier skid penalty.
  CASE
    WHEN multiplied_current IS NULL THEN NULL
    WHEN COALESCE(losses_last_3, 0) >= 3 THEN
      GREATEST(0, multiplied_current - 25)
    WHEN COALESCE(losses_last_5, 0) >= 3 THEN
      GREATEST(0, multiplied_current - 15)
    WHEN COALESCE(losses_last_3, 0) >= 2 THEN
      GREATEST(0, multiplied_current - 10)
    WHEN most_recent_is_loss THEN
      GREATEST(0, multiplied_current - 5)
    ELSE multiplied_current
  END AS vertex_score,

  CASE
    WHEN ufc_bouts >= 3 THEN
      GREATEST(0, ROUND((
          quality_wins * 0.24
        + championship_pedigree * 0.20
        + era_dominance_all_time * 0.18
        + performance_diff * 0.12
        + finishing_dominance_score * 0.16
        + peak_career * 0.10
        - total_loss_penalty * 0.10
        )
        -- Wave 54: credibility — all-time legacy needs a real
        -- sample; full credibility by 14 UFC bouts (~0.62 floor).
        * LEAST(1.0, 0.62 + 0.38 * LEAST(1.0, ufc_bouts / 14.0))
      ))::integer
    ELSE NULL
  END AS vertex_score_all_time
FROM multiplied;


-- =====================================================================
-- DIVISIONAL — fighter_divisional_vertex_score
-- =====================================================================

DROP VIEW IF EXISTS fighter_divisional_vertex_score CASCADE;

CREATE VIEW fighter_divisional_vertex_score AS
WITH
ufc_record_div AS (
  SELECT
    f.id AS fighter_id,
    b.weight_class AS division,
    COUNT(*)::int AS ufc_bouts,
    COUNT(*) FILTER (WHERE b.winner_id = f.id)::int AS ufc_wins,
    COUNT(*) FILTER (
      WHERE b.winner_id IS NOT NULL AND b.winner_id <> f.id
    )::int AS ufc_losses,
    MAX(e.date) AS last_fight_date
  FROM fighter f
  JOIN bout b ON (b.fighter_a_id = f.id OR b.fighter_b_id = f.id)
  JOIN event e ON e.id = b.event_id
  WHERE b.status = 'completed'
  GROUP BY f.id, b.weight_class
),
ranked_bouts_div AS (
  SELECT
    f.id AS f_id,
    b.weight_class AS division,
    b.winner_id,
    e.date AS event_date,
    ROW_NUMBER() OVER (
      PARTITION BY f.id, b.weight_class
      ORDER BY e.date DESC, b.id DESC
    ) AS rn_desc
  FROM fighter f
  JOIN bout b ON (b.fighter_a_id = f.id OR b.fighter_b_id = f.id)
  JOIN event e ON e.id = b.event_id
  WHERE b.status = 'completed'
),
most_recent_bout_div AS (
  SELECT
    f_id AS fighter_id,
    division,
    (winner_id IS NOT NULL AND winner_id <> f_id) AS most_recent_is_loss
  FROM ranked_bouts_div
  WHERE rn_desc = 1
),
recent_losses_div AS (
  SELECT
    f_id AS fighter_id,
    division,
    COUNT(*) FILTER (
      WHERE rn_desc <= 3 AND winner_id IS NOT NULL AND winner_id <> f_id
    )::int AS losses_last_3,
    COUNT(*) FILTER (
      WHERE rn_desc <= 5 AND winner_id IS NOT NULL AND winner_id <> f_id
    )::int AS losses_last_5,
    COUNT(*) FILTER (
      WHERE event_date > NOW() - INTERVAL '24 months'
        AND winner_id IS NOT NULL AND winner_id <> f_id
    )::int AS losses_24mo
  FROM ranked_bouts_div
  GROUP BY f_id, division
),
recent_losses_weighted_div AS (
  SELECT
    f.id AS fighter_id,
    b.weight_class AS division,
    e.date AS bout_date,
    (b.winner_id IS NOT NULL AND b.winner_id <> f.id) AS is_loss,
    LEAST(1.0, GREATEST(0.6,
      1.0 - COALESCE(bot.opp_tier_value, 0)::float / 30.0
    )) AS severity,
    ROW_NUMBER() OVER (
      PARTITION BY f.id, b.weight_class
      ORDER BY e.date DESC, b.id DESC
    ) AS rn_desc
  FROM fighter f
  JOIN bout b ON (b.fighter_a_id = f.id OR b.fighter_b_id = f.id)
  JOIN event e ON e.id = b.event_id
  LEFT JOIN bout_opponent_tier bot
    ON bot.bout_id = b.id AND bot.fighter_id = f.id
  WHERE b.status = 'completed'
),
recent_loss_penalty_calc_div AS (
  SELECT
    fighter_id,
    division,
    LEAST(100, ROUND(
        COALESCE(SUM(severity) FILTER (WHERE is_loss AND rn_desc <= 3), 0) * 25
      + COALESCE(SUM(severity) FILTER (WHERE is_loss AND rn_desc <= 5), 0) * 12
      + COALESCE(SUM(severity) FILTER (
          WHERE is_loss AND bout_date >= NOW() - INTERVAL '24 months'
        ), 0) * 6
    ))::int AS recent_loss_penalty
  FROM recent_losses_weighted_div
  GROUP BY fighter_id, division
),
bout_fighter_stats_div AS (
  SELECT
    brs.bout_id,
    brs.fighter_id,
    SUM(brs.sig_str_landed)::int          AS sig_str_landed_total,
    SUM(brs.control_time_seconds)::int    AS control_seconds_total,
    SUM(brs.takedowns_landed)::int        AS takedowns_landed_total,
    SUM(brs.knockdowns)::int              AS knockdowns_total,
    SUM(brs.sub_attempts)::int            AS sub_attempts_total
  FROM bout_round_stats brs
  GROUP BY brs.bout_id, brs.fighter_id
),
recent_bouts_window_div AS (
  SELECT
    bf.bout_id,
    bf.fighter_id,
    b.weight_class AS division,
    (b.winner_id = bf.fighter_id) AS is_win,
    e.date AS bout_date,
    b.method::text AS method,
    CASE
      WHEN b.round_finished IS NULL THEN COALESCE(b.scheduled_rounds, 3) * 300
      ELSE (b.round_finished - 1) * 300 + COALESCE(b.time_finished_seconds, 300)
    END AS bout_fight_seconds,
    COALESCE(bot.opp_tier_value, 0) AS opp_tier_value,
    COALESCE(bfs.sig_str_landed_total, 0)        AS sig_landed,
    COALESCE(bfs_opp.sig_str_landed_total, 0)    AS sig_absorbed,
    COALESCE(bfs.control_seconds_total, 0)       AS control_seconds,
    COALESCE(bfs.takedowns_landed_total, 0)      AS td_landed,
    COALESCE(bfs_opp.takedowns_landed_total, 0)  AS opp_td_landed,
    COALESCE(bfs.knockdowns_total, 0)            AS kd_total,
    COALESCE(bfs.sub_attempts_total, 0)          AS sa_total,
    ROW_NUMBER() OVER (
      PARTITION BY bf.fighter_id, b.weight_class
      ORDER BY e.date DESC, b.id DESC
    ) AS recency_rank
  FROM (
    SELECT id AS bout_id, fighter_a_id AS fighter_id, fighter_b_id AS opp_id
    FROM bout WHERE status = 'completed'
    UNION ALL
    SELECT id AS bout_id, fighter_b_id AS fighter_id, fighter_a_id AS opp_id
    FROM bout WHERE status = 'completed'
  ) bf
  JOIN bout b ON b.id = bf.bout_id
  JOIN event e ON e.id = b.event_id
  LEFT JOIN bout_opponent_tier bot
    ON bot.bout_id = bf.bout_id AND bot.fighter_id = bf.fighter_id
  LEFT JOIN bout_fighter_stats_div bfs
    ON bfs.bout_id = bf.bout_id AND bfs.fighter_id = bf.fighter_id
  LEFT JOIN bout_fighter_stats_div bfs_opp
    ON bfs_opp.bout_id = bf.bout_id AND bfs_opp.fighter_id = bf.opp_id
),
recent_performance_div AS (
  SELECT
    fighter_id,
    division,
    COUNT(*) AS recent_bout_count,
    AVG(
      LEAST(100, GREATEST(0,
        50 + ((sig_landed - sig_absorbed)::float * 60.0 / NULLIF(bout_fight_seconds, 0)) * 20.0
      ))
    ) AS recent_striking_dominance,
    AVG(
      CASE
        WHEN bout_fight_seconds = 0 THEN 50.0
        ELSE LEAST(100, GREATEST(0,
          50 + ((control_seconds::float / NULLIF(bout_fight_seconds, 0) * 60.0) - 15.0) * 2.6
        ))
      END
    ) AS recent_control_dominance,
    AVG(
      LEAST(100, GREATEST(0,
        50 + ((td_landed - opp_td_landed)::float * 900.0 / NULLIF(bout_fight_seconds, 0)) * 5.0
      ))
    ) AS recent_td_dominance,
    AVG(
      LEAST(100, GREATEST(0,
        50 + ((sig_landed - sig_absorbed)::float * 60.0 / NULLIF(bout_fight_seconds, 0)) * 20.0
      )) - LEAST(90.0, 50.0 + (50.0 - LEAST(50.0, opp_tier_value::float * 2.0)))
    ) AS recent_adjusted_delta
  FROM recent_bouts_window_div
  WHERE recency_rank <= 5
  GROUP BY fighter_id, division
),
-- Wave 31.8: per-axis 0..100 diff dimensions, div-scoped. Mirrors the
-- global view's recent_performance_dims — feeds the Wave 22 max+balance
-- performance_diff_current.
recent_performance_dims_div AS (
  SELECT
    fighter_id,
    division,
    recent_bout_count,
    LEAST(100.0, GREATEST(0.0,
      COALESCE(recent_striking_dominance, 50) + COALESCE(recent_adjusted_delta, 0) * 0.5
    ))::float AS striking_diff_score,
    LEAST(100.0, GREATEST(0.0,
      COALESCE(recent_control_dominance, 50) + COALESCE(recent_adjusted_delta, 0) * 0.3
    ))::float AS control_diff_score,
    LEAST(100.0, GREATEST(0.0,
      COALESCE(recent_td_dominance, 50)
    ))::float AS td_diff_score
  FROM recent_performance_div
),
-- Wave 55: scorecard margin per (bout, fighter). SUM over every
-- (judge, round) cell, ÷ judges ÷ rounds = margin per round. A 30-27
-- sweep or a 50-45 = 1.0/round; a 10-8 round lifts it; a split dips
-- toward 0. ~81% of decision bouts have mmadecisions.com scorecards.
scorecard_margin AS (
  SELECT
    sc.bout_id,
    side.fighter_id,
    (
      SUM(
        CASE WHEN side.is_a
          THEN sc.fighter_a_score - sc.fighter_b_score
          ELSE sc.fighter_b_score - sc.fighter_a_score
        END
      )::float
      / NULLIF(COUNT(DISTINCT sc.judge_name), 0)
      / NULLIF(COUNT(DISTINCT sc.round), 0)
    ) AS margin_per_round
  FROM bout_scorecard sc
  JOIN bout b ON b.id = sc.bout_id
  CROSS JOIN LATERAL (VALUES
    (b.fighter_a_id, TRUE),
    (b.fighter_b_id, FALSE)
  ) AS side(fighter_id, is_a)
  GROUP BY sc.bout_id, side.fighter_id, side.is_a
),
recent_form_div_contributions AS (
  SELECT
    rbw.fighter_id,
    rbw.division,
    rbw.recency_rank,
    CASE
      WHEN rbw.is_win IS NULL THEN 0
      WHEN rbw.method IS NOT NULL
        AND LOWER(rbw.method) LIKE '%no_contest%' THEN 0
      WHEN rbw.is_win THEN rbw.opp_tier_value::float * (
        -- Wave 55: win-quality — finish 1.15; decision scaled
        -- 0.90 (razor split) .. 1.10 (blowout) by scorecard
        -- margin/round; decision with no scorecard → 1.00.
        CASE
          WHEN LOWER(COALESCE(rbw.method, '')) LIKE 'ko%'
            OR LOWER(COALESCE(rbw.method, '')) LIKE 'tko%'
            OR LOWER(COALESCE(rbw.method, '')) LIKE 'sub%' THEN 1.15
          WHEN sm.margin_per_round IS NULL THEN 1.00
          ELSE 0.90 + 0.10 * LEAST(2.0, GREATEST(0.0, sm.margin_per_round))
        END
      )
      ELSE -(rbw.opp_tier_value::float) *
        CASE
          WHEN rbw.opp_tier_value >= 25 THEN 0.30
          WHEN rbw.opp_tier_value >= 22 THEN 0.45
          WHEN rbw.opp_tier_value >= 14 THEN 0.60
          WHEN rbw.opp_tier_value >= 8  THEN 0.75
          WHEN rbw.opp_tier_value >= 3  THEN 0.90
          ELSE 1.00
        END
    END AS contribution,
    CASE rbw.recency_rank
      WHEN 1 THEN 2.00
      WHEN 2 THEN 1.50
      WHEN 3 THEN 1.00
      WHEN 4 THEN 0.75
      WHEN 5 THEN 0.50
      ELSE 0.00
    END::float AS recency_weight
  FROM recent_bouts_window_div rbw
  LEFT JOIN scorecard_margin sm
    ON sm.bout_id = rbw.bout_id AND sm.fighter_id = rbw.fighter_id
  WHERE rbw.recency_rank <= 5
),
recent_form_div AS (
  SELECT
    fighter_id,
    division,
    LEAST(100, GREATEST(0, ROUND(
      50.0
      + (SUM(contribution * recency_weight) / NULLIF(SUM(recency_weight), 0))
        * 1.50
    )))::int AS recent_form_score,
    COUNT(*) AS recent_bout_count
  FROM recent_form_div_contributions
  GROUP BY fighter_id, division
),
months_since_last_div AS (
  SELECT
    ur.fighter_id,
    ur.division,
    CASE
      WHEN ur.last_fight_date IS NULL THEN NULL
      ELSE EXTRACT(EPOCH FROM (NOW() - ur.last_fight_date)) / (60.0 * 60 * 24 * 30.4375)
    END AS m
  FROM ufc_record_div ur
),
recent_title_fight_counts_div AS (
  SELECT
    f.id AS fighter_id,
    b.weight_class AS division,
    COUNT(*) FILTER (
      WHERE e.date >= NOW() - INTERVAL '24 months'
    )::int AS tf_24mo,
    COUNT(*) FILTER (
      WHERE e.date >= NOW() - INTERVAL '36 months'
    )::int AS tf_36mo
  FROM fighter f
  JOIN bout b ON (b.fighter_a_id = f.id OR b.fighter_b_id = f.id)
  JOIN event e ON e.id = b.event_id
  -- Wave 60: curated title fights (title_fight_bout) — the scraped
  -- is_title_fight flag over-counts (bonus icons share the belt cell).
  WHERE b.status = 'completed'
    AND EXISTS (SELECT 1 FROM title_fight_bout tfb WHERE tfb.bout_id = b.id)
  GROUP BY f.id, b.weight_class
),
bout_decay_div AS (
  SELECT
    f.id AS fighter_id,
    b.id AS bout_id,
    b.weight_class AS division,
    e.date AS bout_date,
    (b.winner_id = f.id) AS is_win,
    (
      LOWER(COALESCE(b.method::text, '')) LIKE 'ko%'
      OR LOWER(COALESCE(b.method::text, '')) LIKE 'tko%'
      OR LOWER(COALESCE(b.method::text, '')) LIKE 'sub%'
      OR (b.method IS NULL AND COALESCE(bfs.knockdowns_total, 0) > 0)
      OR (b.method IS NULL AND COALESCE(bfs.sub_attempts_total, 0) > 0)
    ) AS is_finish_method,
    COALESCE(bot.opp_tier_value, 0) AS opp_tier_value,
    GREATEST(0.1, LEAST(1.0,
      CASE
        WHEN (EXTRACT(EPOCH FROM (NOW() - e.date)) / (365.25 * 86400)) <= 1.0 THEN 1.0
        WHEN (EXTRACT(EPOCH FROM (NOW() - e.date)) / (365.25 * 86400)) <= 3.0 THEN
          1.0 - 0.7 * ((EXTRACT(EPOCH FROM (NOW() - e.date)) / (365.25 * 86400)) - 1.0) / 2.0
        WHEN (EXTRACT(EPOCH FROM (NOW() - e.date)) / (365.25 * 86400)) <= 5.0 THEN
          0.3 - 0.2 * ((EXTRACT(EPOCH FROM (NOW() - e.date)) / (365.25 * 86400)) - 3.0) / 2.0
        ELSE 0.1
      END
    ))::float AS decay_factor
  FROM fighter f
  JOIN bout b ON (b.fighter_a_id = f.id OR b.fighter_b_id = f.id)
  JOIN event e ON e.id = b.event_id
  LEFT JOIN bout_opponent_tier bot ON bot.bout_id = b.id AND bot.fighter_id = f.id
  LEFT JOIN bout_fighter_stats_div bfs ON bfs.bout_id = b.id AND bfs.fighter_id = f.id
  WHERE b.status = 'completed'
),
quality_wins_decayed_calc_div AS (
  SELECT
    fighter_id,
    division,
    LEAST(100.0, COALESCE(
      SUM(opp_tier_value::float * decay_factor) FILTER (WHERE is_win),
      0
    ))::float AS quality_wins_decayed
  FROM bout_decay_div
  GROUP BY fighter_id, division
),
finishing_dom_decayed_calc_div AS (
  SELECT
    fighter_id,
    division,
    CASE
      WHEN COALESCE(SUM(decay_factor) FILTER (WHERE is_win), 0) = 0 THEN 0.0
      ELSE 100.0
        * COALESCE(SUM(decay_factor) FILTER (WHERE is_win AND is_finish_method), 0)
        / SUM(decay_factor) FILTER (WHERE is_win)
    END::float AS finishing_dominance_decayed
  FROM bout_decay_div
  GROUP BY fighter_id, division
),
-- Wave 31.8: career-wide KD-received (Wave 30). Not div-scoped — a
-- counter to opponent knockdowns is a career style trait. Copied
-- verbatim from the global view (migration 0068).
kd_received_calc AS (
  SELECT
    f.id AS fighter_id,
    COALESCE(SUM(brs.knockdowns), 0)::float AS total_kd_received,
    COUNT(DISTINCT b.id)::int AS bouts_counted,
    CASE
      WHEN COUNT(DISTINCT b.id) > 0 THEN
        COALESCE(SUM(brs.knockdowns), 0)::float / COUNT(DISTINCT b.id)::float
      ELSE 0.0
    END AS kd_received_per_fight
  FROM fighter f
  LEFT JOIN bout b
    ON (b.fighter_a_id = f.id OR b.fighter_b_id = f.id)
    AND b.status = 'completed'
  LEFT JOIN bout_round_stats brs
    ON brs.bout_id = b.id
    AND brs.fighter_id = CASE
      WHEN b.fighter_a_id = f.id THEN b.fighter_b_id
      ELSE b.fighter_a_id
    END
  GROUP BY f.id
),
-- Wave 31.8: career-wide style intents + defensive weaknesses (Wave
-- 26/30). Copied verbatim from the global view.
defensive_vulnerability_calc AS (
  SELECT
    f.id AS fighter_id,
    LEAST(1.0, COALESCE(fsa.slpm, 0)::float / 5.0)::float AS striker_intent,
    LEAST(1.0, COALESCE(fsa.td_avg, 0)::float / 2.0)::float AS wrestler_intent,
    (GREATEST(0.0, 0.55 - COALESCE(fsa.td_def, 0.55)::float) / 0.55)::float
      AS td_def_weakness,
    (GREATEST(0.0, 0.55 - COALESCE(fsa.str_def, 0.55)::float) / 0.55)::float
      AS str_def_weakness,
    (LEAST(1.0, GREATEST(0.0, COALESCE(fsa.sapm, 0)::float - 4.0) / 4.0))::float
      AS sapm_weakness,
    (LEAST(1.0, GREATEST(0.0,
      COALESCE(kdr.kd_received_per_fight, 0.0) - 0.15
    ) / 0.25))::float AS kd_received_weakness
  FROM fighter f
  LEFT JOIN fighter_stats_aggregate fsa ON fsa.fighter_id = f.id
  LEFT JOIN kd_received_calc kdr ON kdr.fighter_id = f.id
),
defensive_vulnerability_score AS (
  SELECT
    fighter_id,
    LEAST(100.0, GREATEST(0.0,
      (
        striker_intent * td_def_weakness
        + wrestler_intent * (
            str_def_weakness * 0.45
          + sapm_weakness * 0.25
          + kd_received_weakness * 0.30
        )
      ) * 100.0
    ))::float AS defensive_vulnerability
  FROM defensive_vulnerability_calc
),
fighter_age_calc_div AS (
  SELECT
    f.id AS fighter_id,
    CASE
      WHEN f.dob IS NULL THEN NULL
      ELSE FLOOR(EXTRACT(EPOCH FROM (NOW() - f.dob)) / (365.25 * 86400))::int
    END AS age_years,
    CASE
      WHEN f.dob IS NULL THEN 0.00
      WHEN FLOOR(EXTRACT(EPOCH FROM (NOW() - f.dob)) / (365.25 * 86400)) < 26 THEN 0.00
      WHEN FLOOR(EXTRACT(EPOCH FROM (NOW() - f.dob)) / (365.25 * 86400)) <= 30 THEN  0.05
      WHEN FLOOR(EXTRACT(EPOCH FROM (NOW() - f.dob)) / (365.25 * 86400)) <= 32 THEN  0.02
      WHEN FLOOR(EXTRACT(EPOCH FROM (NOW() - f.dob)) / (365.25 * 86400)) <= 34 THEN  0.00
      WHEN FLOOR(EXTRACT(EPOCH FROM (NOW() - f.dob)) / (365.25 * 86400)) <= 36 THEN -0.04
      WHEN FLOOR(EXTRACT(EPOCH FROM (NOW() - f.dob)) / (365.25 * 86400)) <= 38 THEN -0.08
      ELSE -0.12
    END::float AS age_factor
  FROM fighter f
),
components_div AS (
  SELECT
    ur.fighter_id,
    ur.division,
    f.slug,
    f.gender,
    f.roster_status::text AS roster_status,
    f.current_division AS fighter_current_division,
    f.has_upcoming_bout,
    COALESCE(f.current_streak, 0) AS current_streak,
    ur.ufc_bouts AS bouts_in_division,
    ur.ufc_wins,
    ur.ufc_losses,
    ur.last_fight_date AS last_fight_date_in_division,

    (
      f.roster_status = 'active'
      AND ur.last_fight_date IS NOT NULL
      AND ur.last_fight_date > NOW() - INTERVAL '24 months'
    ) AS is_active_in_division,

    COALESCE(rl.losses_last_3, 0) AS losses_last_3,
    COALESCE(rl.losses_last_5, 0) AS losses_last_5,
    COALESCE(rl.losses_24mo, 0) AS losses_24mo,

    COALESCE(mrb.most_recent_is_loss, FALSE) AS most_recent_is_loss,

    COALESCE(qwd.quality_wins_decayed, 0)::float AS quality_wins_decayed,
    -- Wave 60: 0-100 parity (was 0-10). Title fight in 24mo → 50,
    -- ≥2 title fights in 36mo → +50. Same signal, ×10 scale — at the
    -- unchanged 0.06 weight the component now contributes up to 6.0
    -- raw points (was 0.6), in line with its 0-100-scale neighbours.
    LEAST(100,
      (CASE WHEN COALESCE(rtfc.tf_24mo, 0) >= 1 THEN 50 ELSE 0 END)
    + (CASE WHEN COALESCE(rtfc.tf_36mo, 0) >= 2 THEN 50 ELSE 0 END)
    )::float AS era_dominance_current,
    (COALESCE(rtfc.tf_24mo, 0) >= 1) AS had_title_fight_recently,
    COALESCE(rfm.recent_form_score, 50)::int AS recent_form_score,

    -- Wave 31.8: Wave 21 layered activity — max over 12/24/36mo windows
    -- of (fights × avg opp tier / period target × 100). Replaces the old
    -- step-function fade (≈100 for any active fighter), which made the
    -- divisional score overshoot global. Uses the career fights_last_Nmo
    -- columns; the divisional rows kept are all the fighter's current
    -- division, so career activity == divisional activity. Identical to
    -- the global view.
    GREATEST(
      LEAST(100.0,
        COALESCE(f.fights_last_12mo, 0)::float
        * COALESCE(f.avg_opp_tier_last_12mo, 0)::float / 60.0 * 100.0
      ),
      LEAST(100.0,
        COALESCE(f.fights_last_24mo, 0)::float
        * COALESCE(f.avg_opp_tier_last_24mo, 0)::float / 120.0 * 100.0
      ),
      LEAST(100.0,
        COALESCE(f.fights_last_36mo, 0)::float
        * COALESCE(f.avg_opp_tier_last_36mo, 0)::float / 180.0 * 100.0
      )
    )::float AS activity,

    COALESCE(rlp.recent_loss_penalty, 0)::float AS recent_loss_penalty,

    -- Wave 31.8: Wave 22 max + balance. Strongest of the three axes,
    -- lifted up to +25% by how balanced the weaker two are. Specialists
    -- keep full credit; universalists earn the bonus.
    CASE
      WHEN rpd.recent_bout_count IS NULL OR rpd.recent_bout_count = 0 THEN 50.0
      ELSE LEAST(100.0,
        GREATEST(rpd.striking_diff_score, rpd.control_diff_score, rpd.td_diff_score)
        * (
          1.0
          + 0.25
            * LEAST(rpd.striking_diff_score, rpd.control_diff_score, rpd.td_diff_score)
              / GREATEST(GREATEST(rpd.striking_diff_score, rpd.control_diff_score, rpd.td_diff_score), 1.0)
        )
      )
    END::float AS performance_diff_current,

    COALESCE(fdd.finishing_dominance_decayed, 0)::float AS finishing_dominance_decayed,

    -- Wave 31.8: career-wide style-weighted defensive vulnerability.
    COALESCE(dvs.defensive_vulnerability, 0)::float AS defensive_vulnerability,

    fac.age_years,
    COALESCE(fac.age_factor, 0.0)::float AS age_factor,
    msl.m::float AS months_since_last,
    CASE
      WHEN msl.m IS NULL OR msl.m <= 12 THEN 0.0
      ELSE LEAST(15.0, (msl.m - 12.0) * 0.5)
    END::float AS layoff_penalty

  FROM ufc_record_div ur
  JOIN fighter f ON f.id = ur.fighter_id
  LEFT JOIN recent_losses_div rl
    ON rl.fighter_id = ur.fighter_id AND rl.division = ur.division
  LEFT JOIN most_recent_bout_div mrb
    ON mrb.fighter_id = ur.fighter_id AND mrb.division = ur.division
  LEFT JOIN recent_loss_penalty_calc_div rlp
    ON rlp.fighter_id = ur.fighter_id AND rlp.division = ur.division
  LEFT JOIN recent_performance_dims_div rpd
    ON rpd.fighter_id = ur.fighter_id AND rpd.division = ur.division
  LEFT JOIN recent_form_div rfm
    ON rfm.fighter_id = ur.fighter_id AND rfm.division = ur.division
  LEFT JOIN months_since_last_div msl
    ON msl.fighter_id = ur.fighter_id AND msl.division = ur.division
  LEFT JOIN recent_title_fight_counts_div rtfc
    ON rtfc.fighter_id = ur.fighter_id AND rtfc.division = ur.division
  LEFT JOIN quality_wins_decayed_calc_div qwd
    ON qwd.fighter_id = ur.fighter_id AND qwd.division = ur.division
  LEFT JOIN finishing_dom_decayed_calc_div fdd
    ON fdd.fighter_id = ur.fighter_id AND fdd.division = ur.division
  LEFT JOIN defensive_vulnerability_score dvs
    ON dvs.fighter_id = ur.fighter_id
  LEFT JOIN fighter_age_calc_div fac
    ON fac.fighter_id = ur.fighter_id
)
SELECT
  fighter_id,
  slug,
  gender,
  division,
  roster_status,
  fighter_current_division,
  has_upcoming_bout,
  bouts_in_division,
  ufc_wins,
  ufc_losses,
  last_fight_date_in_division,
  is_active_in_division,
  losses_last_3,
  losses_last_5,
  losses_24mo,
  most_recent_is_loss,

  quality_wins_decayed,
  era_dominance_current,
  had_title_fight_recently,
  recent_form_score,
  activity,
  recent_loss_penalty,
  performance_diff_current,
  finishing_dominance_decayed,
  defensive_vulnerability,

  age_years,
  age_factor,
  months_since_last,
  layoff_penalty,

  -- Wave 31.8: defensive_vulnerability subtracted in-view alongside
  -- layoff_penalty. The age multiplier + current_cp injection happen in
  -- materialize_divisional_score.ts, matching the global view's
  -- (positives + cp - penalties) × (1 + age_factor) structure.
  (
      quality_wins_decayed * 0.16
    + era_dominance_current * 0.06
    + performance_diff_current * 0.16
    + finishing_dominance_decayed * 0.10
    + activity * 0.12
    + recent_form_score::float * 0.18
    - recent_loss_penalty * 0.20
    - defensive_vulnerability * 0.10
    - layoff_penalty
    -- Wave 32: win-streak bonus (raw points, +0..5).
    + LEAST(5.0, GREATEST(0.0, current_streak - 2))
  )::float AS raw_current_excl_cp
FROM components_div
WHERE bouts_in_division >= 3;
