/**
 * Generates drizzle/migrations/0075_wave54_credibility_factor.sql from the
 * current view migration (0074).
 *
 * Wave 54 — sample-size credibility. A thin résumé is a noisy résumé:
 * Topuria (9-0, 9 bouts) maxed the formula with no résumé-depth check.
 * Adds a bout-count multiplier, ASYMMETRIC by design:
 *
 *   current : LEAST(1, 0.85 + 0.15 × min(1, ufc_bouts/12))  — mild,
 *             0.85-1.0, full credibility by 12 bouts. Current form is
 *             judgeable on a shorter window.
 *   all-time: LEAST(1, 0.62 + 0.38 × min(1, ufc_bouts/14))  — strong,
 *             0.62-1.0. A legacy needs a real sample; a 9-bout phenom
 *             is not yet an all-time great.
 *
 * Effect: Topuria current 88→~85, all-time 87→~75. Khabib (13 bouts)
 * all-time barely touched (~0.97). 15+ bout fighters unaffected.
 *
 * The divisional view's current credibility is applied in
 * materialize_divisional_score.ts (same commit) using bouts_in_division.
 *
 * GENERATED — two asserted string transforms over 0074 (global view
 * only; the divisional view passes through). Do not hand-edit.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

function replaceOnce(haystack: string, needle: string, repl: string): string {
  const n = haystack.split(needle).length - 1;
  if (n !== 1) {
    throw new Error(
      `Expected exactly 1 occurrence of anchor, found ${n}:\n${needle}`,
    );
  }
  return haystack.replace(needle, repl);
}

function body(sql: string): string {
  const i = sql.indexOf("DROP VIEW");
  if (i < 0) throw new Error("DROP VIEW not found");
  return sql.slice(i);
}

function main() {
  const src = readFileSync(
    resolve(
      "drizzle/migrations/0074_wave53_alltime_peak_and_weighted_losses.sql",
    ),
    "utf8",
  );
  let v = body(src);

  // --- T1: current-score credibility — multiply raw_current ---
  v = replaceOnce(
    v,
    "          ) * (1.0 + age_factor)\n        )",
    "          ) * (1.0 + age_factor)\n" +
      "            -- Wave 54: credibility — current score is mildly\n" +
      "            -- damped for thin résumés (full credibility by 12\n" +
      "            -- UFC bouts, 0.85 floor).\n" +
      "            * LEAST(1.0, 0.85 + 0.15 * LEAST(1.0, ufc_bouts / 12.0))\n" +
      "        )",
  );

  // --- T2: all-time credibility — multiply the weighted sum ---
  v = replaceOnce(
    v,
    "      GREATEST(0, ROUND(\n" +
      "          quality_wins * 0.24\n" +
      "        + championship_pedigree * 0.20\n" +
      "        + era_dominance_all_time * 0.18\n" +
      "        + performance_diff * 0.12\n" +
      "        + finishing_dominance_score * 0.16\n" +
      "        + peak_career * 0.10\n" +
      "        - total_loss_penalty * 0.10\n" +
      "      ))::integer",
    "      GREATEST(0, ROUND((\n" +
      "          quality_wins * 0.24\n" +
      "        + championship_pedigree * 0.20\n" +
      "        + era_dominance_all_time * 0.18\n" +
      "        + performance_diff * 0.12\n" +
      "        + finishing_dominance_score * 0.16\n" +
      "        + peak_career * 0.10\n" +
      "        - total_loss_penalty * 0.10\n" +
      "        )\n" +
      "        -- Wave 54: credibility — all-time legacy needs a real\n" +
      "        -- sample; full credibility by 14 UFC bouts (~0.62 floor).\n" +
      "        * LEAST(1.0, 0.62 + 0.38 * LEAST(1.0, ufc_bouts / 14.0))\n" +
      "      ))::integer",
  );

  const header = `-- Wave 54: sample-size credibility factor.
--
-- A thin résumé is a noisy résumé. Topuria (9-0, 9 UFC bouts) maxed the
-- formula because nothing checked résumé depth. Adds a bout-count
-- multiplier, asymmetric by design:
--
--   current : LEAST(1, 0.85 + 0.15 × min(1, ufc_bouts/12)) — mild,
--             0.85-1.0. Current form is judgeable on a short window.
--   all-time: LEAST(1, 0.62 + 0.38 × min(1, ufc_bouts/14)) — strong,
--             0.62-1.0. A legacy needs a real sample.
--
-- Effect: Topuria current 88→~85, all-time 87→~75. Khabib (13 bouts)
-- all-time barely touched. 15+ bout fighters unaffected.
--
-- The divisional view's current credibility is applied in
-- materialize_divisional_score.ts (same commit), keyed on
-- bouts_in_division — so the divisional score's confidence reflects
-- bouts IN that division. The divisional view itself is unchanged here.
--
-- GENERATED by scripts/generate_wave54.ts from 0074 — do not hand-edit.
--
-- Re-materialize after applying:
--   pnpm tsx scripts/materialize_vertex_score.ts
--   pnpm tsx scripts/materialize_divisional_score.ts

${v}`;

  const out = resolve(
    "drizzle/migrations/0075_wave54_credibility_factor.sql",
  );
  writeFileSync(out, header, "utf8");
  console.log(`Wrote ${out}`);
}

main();
