/**
 * Generates drizzle/migrations/0073_wave33_loss_to_top_severity.sql from
 * the current view migration (0072).
 *
 * Wave 33: a loss to a top opponent should register. recent_loss_penalty
 * weights each loss by `severity`:
 *
 *   severity = LEAST(1.0, GREATEST(floor, 1.0 - opp_tier_value / 30.0))
 *
 * The floor was 0.3 — a loss to an apex champion counted for only 30% of
 * a "full" loss, near-forgiven. Raising the floor to 0.6 makes losses to
 * ranked-tier opponents (opp_tier ≥ 12) count for 60%, while a loss to a
 * journeyman still maxes at 1.0. The gradient direction is unchanged
 * (losing to a nobody is still worse than losing to the champ) — the
 * top end just stops being a free pass.
 *
 * Effect on one recent loss (rn≤3 + rn≤5 + 24mo windows all hit, weight
 * 0.20): loss to an apex opponent goes from ≈ -2.6 to ≈ -5.2 raw points.
 *
 * GENERATED — transforms 0072 with two asserted string replacements
 * (global recent_losses_weighted + divisional recent_losses_weighted_div).
 */
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

function replaceN(
  haystack: string,
  needle: string,
  repl: string,
  expected: number,
): string {
  const n = haystack.split(needle).length - 1;
  if (n !== expected) {
    throw new Error(
      `Expected ${expected} occurrences of anchor, found ${n}:\n${needle}`,
    );
  }
  return haystack.split(needle).join(repl);
}

function body(sql: string): string {
  const i = sql.indexOf("DROP VIEW");
  if (i < 0) throw new Error("DROP VIEW not found");
  return sql.slice(i);
}

function main() {
  const src = readFileSync(
    resolve("drizzle/migrations/0072_wave32_streak_bonus.sql"),
    "utf8",
  );

  // The severity floor appears once per view (global recent_losses_weighted
  // and divisional recent_losses_weighted_div) — exactly 2.
  const transformed = replaceN(
    body(src),
    "LEAST(1.0, GREATEST(0.3,",
    "LEAST(1.0, GREATEST(0.6,",
    2,
  );

  const header = `-- Wave 33: a loss to a top opponent should register.
--
-- recent_loss_penalty weights each loss by severity:
--   severity = LEAST(1.0, GREATEST(floor, 1.0 - opp_tier_value / 30.0))
--
-- Floor raised 0.3 → 0.6. A loss to an apex/ranked opponent (opp_tier
-- ≥ 12) now counts for 60% of a full loss instead of 30% — it stops
-- being a near-free pass. A loss to a journeyman still maxes at 1.0;
-- the gradient direction is unchanged (losing to a nobody is worse than
-- losing to the champ), the top end just bites now.
--
-- One recent loss to an apex opponent: ≈ -2.6 → ≈ -5.2 raw points.
-- Applied to both fighter_vertex_score and fighter_divisional_vertex_score.
--
-- GENERATED by scripts/generate_wave33.ts from 0072 — do not hand-edit.
--
-- Re-materialize after applying:
--   pnpm tsx scripts/materialize_vertex_score.ts
--   pnpm tsx scripts/materialize_divisional_score.ts

${transformed}`;

  const out = resolve(
    "drizzle/migrations/0073_wave33_loss_to_top_severity.sql",
  );
  writeFileSync(out, header, "utf8");
  console.log(`Wrote ${out}`);
}

main();
