/**
 * Generates drizzle/migrations/0072_wave32_streak_bonus.sql from the two
 * current view migrations (0068 global, 0071 divisional).
 *
 * Wave 32 adds a win-streak bonus to current_score. fighter.current_streak
 * (from roster.watch — positive = win streak) was computed and surfaced
 * but never fed into raw_current. The bonus is a small raw-point term:
 *
 *   streak_bonus = LEAST(5, GREATEST(0, current_streak - 2))
 *
 * 0 below a 3-fight streak, then +1 per win, capped at +5 (streak ≥ 7).
 * Losing streaks (negative current_streak) get 0 — they're already
 * handled by recent_loss_penalty + the skid ladder.
 *
 * Rather than hand-reproduce ~1300 lines of view SQL, this transforms
 * the existing migration files with three asserted string replacements.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

function replaceOnce(haystack: string, needle: string, repl: string): string {
  const n = haystack.split(needle).length - 1;
  if (n !== 1) {
    throw new Error(
      `Expected exactly 1 occurrence of anchor, found ${n}:\n${needle}`,
    );
  }
  return haystack.replace(needle, repl);
}

/** Strip a file's leading comment header — keep from `DROP VIEW` onward. */
function body(sql: string): string {
  const i = sql.indexOf("DROP VIEW");
  if (i < 0) throw new Error("DROP VIEW not found");
  return sql.slice(i);
}

const STREAK = "LEAST(5.0, GREATEST(0.0, current_streak - 2))";

function main() {
  const globalSrc = readFileSync(
    resolve("drizzle/migrations/0068_wave31_age_layoff_ceiling_recency.sql"),
    "utf8",
  );
  const divSrc = readFileSync(
    resolve("drizzle/migrations/0071_wave31_8_divisional_full_parity.sql"),
    "utf8",
  );

  // --- Global: add the streak bonus inside raw_current ---
  // current_streak is already a column on the `components` CTE, so it's
  // visible in raw_scores via SELECT *.
  let g = body(globalSrc);
  g = replaceOnce(
    g,
    "            - layoff_penalty\n          ) * (1.0 + age_factor)",
    "            - layoff_penalty\n" +
      "            -- Wave 32: win-streak bonus (raw points, +0..5).\n" +
      `            + ${STREAK}\n` +
      "          ) * (1.0 + age_factor)",
  );

  // --- Divisional: expose current_streak on components_div, then add the
  //     bonus inside raw_current_excl_cp ---
  let d = body(divSrc);
  d = replaceOnce(
    d,
    "    f.has_upcoming_bout,\n    ur.ufc_bouts AS bouts_in_division,",
    "    f.has_upcoming_bout,\n" +
      "    COALESCE(f.current_streak, 0) AS current_streak,\n" +
      "    ur.ufc_bouts AS bouts_in_division,",
  );
  d = replaceOnce(
    d,
    "    - layoff_penalty\n  )::float AS raw_current_excl_cp",
    "    - layoff_penalty\n" +
      "    -- Wave 32: win-streak bonus (raw points, +0..5).\n" +
      `    + ${STREAK}\n` +
      "  )::float AS raw_current_excl_cp",
  );

  const header = `-- Wave 32: win-streak bonus.
--
-- fighter.current_streak (roster.watch; positive = current win streak)
-- was computed and surfaced by both views but never used in the score.
-- This adds it as a small raw-point bonus:
--
--   streak_bonus = LEAST(5, GREATEST(0, current_streak - 2))
--
-- 0 below a 3-fight streak, +1 per win after, capped at +5 (streak ≥ 7).
-- Losing streaks (negative) get 0 — already covered by recent_loss_penalty
-- and the skid ladder. Applied to BOTH the global view's raw_current and
-- the divisional view's raw_current_excl_cp so they stay in parity.
--
-- GENERATED by scripts/generate_wave32.ts from 0068 (global, Wave 31) +
-- 0071 (divisional, Wave 31.8) — do not hand-edit; re-run the generator.
--
-- Re-materialize after applying:
--   pnpm tsx scripts/materialize_vertex_score.ts
--   pnpm tsx scripts/materialize_divisional_score.ts

-- =====================================================================
-- GLOBAL — fighter_vertex_score
-- =====================================================================

${g}

-- =====================================================================
-- DIVISIONAL — fighter_divisional_vertex_score
-- =====================================================================

${d}`;

  const out = resolve("drizzle/migrations/0072_wave32_streak_bonus.sql");
  writeFileSync(out, header, "utf8");
  console.log(`Wrote ${out}`);
}

main();
